instruments = {'bibox': ['BTC_USDT', 'ETH_USDT', 'BCH_USDT', 'XRP_USDT', 'LTC_USDT', 'BSV_USDT', 'EOS_BTC', 'EOS_USDT', 'BCH_BTC', 'ETH_BTC', 'LTC_BTC', 'ONG_BTC', 'HYN_ETH', 'ONG_ETH', 'ONG_USDT', 'EOS_ETH',
                         'LINK_USDT', 'TRX_USDT', 'ETC_USDT', 'ETC_BTC', 'BCH_ETH', 'XRP_BTC', 'XRP_ETH', 'HYN_BTC', 'LTC_ETH', 'LINK_BTC', 'HYN_USDT', 'OMG_USDT', 'NEO_BTC', 'RDN_ETH', 'LEND_USDT', 'BSV_BTC',
                         'LEND_BTC', 'TRX_BTC', 'ATOM_USDT', 'ONT_USDT', 'ETC_ETH', 'TNB_ETH', 'TRX_ETH', 'BIX_ETH', 'OMG_BTC', 'BTM_USDT', 'QTUM_USDT', 'LINK_ETH', 'BSV_ETH', 'BIX_BTC', 'HT_USDT', 'REP_BTC',
                         'MKR_USDT', 'DASH_USDT', 'MKR_BTC', 'REP_ETH', 'REP_USDT', 'NEO_ETH', 'NEO_USDT', 'LEND_ETH', 'NULS_BTC', 'NULS_USDT', 'BTM_BTC', 'HEX_USDT', 'ABBC_USDT', 'ONT_BTC', 'ABBC_BTC',
                         'BIX_USDT', 'QTUM_BTC', 'OMG_ETH', 'MKR_ETH', 'DASH_BTC', 'HT_BTC', 'IRIS_USDT', 'ALGO_USDT', 'ATOM_ETH', 'ONT_ETH', 'HT_ETH', 'BAT_USDT', 'BTM_ETH', 'LAMB_USDT', 'QTUM_ETH', 'BTT_ETH',
                         'PEAK_USDT', 'ALGO_BTC', 'DASH_ETH', 'IRIS_BTC', 'BAT_BTC', 'BAL_ETH', 'BAL_USDT', 'DNA_USDT', 'IRIS_ETH', 'ALGO_ETH', 'KEY_ETH', 'KSM_ETH', 'MT_USDT', 'MANA_USDT', 'XNK_ETH', 'FTM_USDT',
                         'BAT_ETH', 'LAMB_ETH', 'KSM_USDT', 'HPB_USDT', 'KSM_BTC', 'DOGE_USDT', 'CMT_ETH', 'AG8_USDT', 'HPB_ETH', 'INSTAR_BTC', 'DOGE_ETH', 'CPC_ETH', 'DVP_BTC', 'VNT_ETH',
                         'CPC_USDT', 'CRO_USDT', 'GRIN_ETH', 'GRIN_USDT', 'EOSC_USDT', 'LINK_BIX', 'FSN_USDT', 'EOSDAC_ETH', 'GRIN_BTC', 'OMG_BIX', 'BAT_BIX', 'DVP_ETH', 'MT_ETH', 'ALGO_BIX', 'GNX_ETH', 'ATOM_BIX',
                         'FOR_USDT', 'LBA_USDT', 'HPB_BTC', 'RED_ETH', 'CPC_BTC', 'JNT_BTC', 'BU_ETH', 'ORMEUS_USDT', 'BU_USDT', 'FTM_ETH', 'VNT_USDT', 'ONT_BIX', 'HDAC_BTC', 'PI_ETH', 'TTC_ETH', 'TTC_USDT',
                         'PI_USDT', 'HPB_BIX', 'DOGE_BIX', 'FSN_BTC', 'LIT_BTC', 'KEY_USDT', 'CZR_ETH', 'ITC_ETH', 'EOSDAC_BTC', 'HER_ETH', 'LBA_BTC',
                         'ABT_BTC', 'BCV_BTC', 'MANA_ETH', 'MANA_BTC', 'GTO_BTC', 'ITC_BTC', 'UUU_ETH', 'EGG_USDT', 'MXC_BTC', 'MTC_ETH',
                         'ABT_ETH', 'RTE_ETH', 'ELF_BTC'],

                'binance': 'btcusdt@trade/ethusdt@trade/linkusdt@trade/bchusdt@trade/adausdt@trade/ethbtc@trade/xrpusdt@trade/batusdt@trade/xtzusdt@trade/eosusdt@trade/btcbusd@trade/bnbusdt@trade/busdusdt@trade/'
                          'ltcusdt@trade/vetusdt@trade/zilusdt@trade/ontusdt@trade/etcusdt@trade/lunbtc@trade/zecusdt@trade/bnbbtc@trade/batbtc@trade/btcusdc@trade/linkbtc@trade/ongusdt@trade/xlmusdt@trade/'
                          'zilbtc@trade/usdcusdt@trade/ongbtc@trade/btgbtc@trade/trxusdt@trade/maticusdt@trade/xrpbtc@trade/adabtc@trade/iostusdt@trade/atomusdt@trade/maticbtc@trade/neousdt@trade/bchbtc@trade/'
                          'xvgbtc@trade/zecbtc@trade/ontbtc@trade/eosbtc@trade/edobtc@trade/erdbtc@trade/xmrbtc@trade/btcpax@trade/erdusdt@trade/xtzbtc@trade/xmrusdt@trade/paxusdt@trade/bcdbtc@trade/onebtc@trade/'
                          'solbtc@trade/ethbusd@trade/qtumusdt@trade/rvnbtc@trade/ltcbtc@trade/dashusdt@trade/scbtc@trade/xlmbtc@trade/bateth@trade/zrxusdt@trade/kncbtc@trade/oneusdt@trade/tusdusdt@trade/'
                          'lendbtc@trade/atombtc@trade/hbarbtc@trade/iostbtc@trade/ethusdc@trade/tnbbtc@trade/btctusd@trade/vetbtc@trade/oaxbtc@trade/nulsbtc@trade/zrxbtc@trade/algousdt@trade/omgusdt@trade/'
                          'ognusdt@trade/btcngn@trade/tomobtc@trade/reqbtc@trade/hbarusdt@trade/lendusdt@trade/nulsusdt@trade/kavabtc@trade/neobtc@trade/renbtc@trade/thetausdt@trade/ltobtc@trade/tomousdt@trade/'
                          'dgbbtc@trade/kavausdt@trade/bntusdt@trade/trxbtc@trade/rvnusdt@trade/chrbtc@trade/thetabtc@trade/enjbtc@trade/renusdt@trade/bntbtc@trade/drepbtc@trade/etcbtc@trade/ankrbtc@trade/'
                          'chrusdt@trade/kncusdt@trade/wrxbtc@trade/ognbtc@trade/wrxusdt@trade/celrbtc@trade/tfuelusdt@trade/ctsibtc@trade/qkcbtc@trade/chzbtc@trade/repbtc@trade/bttusdt@trade/algobtc@trade/'
                          'iotausdt@trade/ethzar@trade/gasbtc@trade/cotibtc@trade/dashbtc@trade/winusdt@trade/gobtc@trade/omgbtc@trade/zileth@trade/nknbtc@trade/enjusdt@trade/qtumbtc@trade/ctxcusdt@trade/'
                          'ctxcbtc@trade/beamusdt@trade/ethpax@trade/celrusdt@trade/icxusdt@trade/nanousdt@trade/ankrusdt@trade/ctsiusdt@trade/solbusd@trade/qlcbtc@trade/iotxbtc@trade/bandusdt@trade/nasbtc@trade/'
                          'ethtusd@trade/aionusdt@trade/iotabtc@trade/rlcbtc@trade/tfuelbtc@trade/cotiusdt@trade/nanobtc@trade/loombtc@trade/beambtc@trade/drepusdt@trade/arnbtc@trade/manabtc@trade/chzusdt@trade/'
                          'gvtbtc@trade/linketh@trade/adaeth@trade/aionbtc@trade/zilbusd@trade/eostusd@trade/bnbbusd@trade/icxbtc@trade/eoseth@trade/blzbtc@trade/trxeth@trade/btceur@trade/iotxusdt@trade/'
                          'troybtc@trade/nknusdt@trade/mdtbtc@trade/bandbtc@trade/mcobtc@trade/lendeth@trade/busdngn@trade/xrpeth@trade/phbbtc@trade/polybtc@trade/bnbeth@trade/viabtc@trade/arkbtc@trade/zilbnb@trade/'
                          'perlusdt@trade/kmdbtc@trade/mblusdt@trade/steembtc@trade/maticbusd@trade/fetusdt@trade/edoeth@trade/rlcusdt@trade/wabibtc@trade/brdbtc@trade/usdttry@trade/trxbnb@trade/rdnbtc@trade/'
                          'engbtc@trade/fttbtc@trade/dogeusdt@trade/btttrx@trade/vibbtc@trade/mdabtc@trade/hiveusdt@trade/fetbtc@trade/btsbtc@trade/appcbtc@trade/erdbnb@trade/stratbtc@trade/lrcbtc@trade/'
                          'hotusdt@trade/ambbtc@trade/bchbusd@trade/xrpbusd@trade/skybtc@trade/elfbtc@trade/batbusd@trade/wavesbtc@trade/qspbtc@trade/pptbtc@trade/storjbtc@trade/gntbtc@trade/ftmbtc@trade/'
                          'cmtbtc@trade/adabusd@trade/xrpbnb@trade/funbtc@trade/btctry@trade/zenbtc@trade/cosbtc@trade/veteth@trade/stmxbtc@trade/bchpax@trade/mblbtc@trade/linkusdc@trade/iqbusd@trade/bqxbtc@trade/'
                          'stmxusdt@trade/perlbtc@trade/bchtusd@trade/ltousdt@trade/hivebtc@trade/dogebtc@trade/xembtc@trade/xvgeth@trade/astbtc@trade/sceth@trade/wanbtc@trade/cosusdt@trade/linkbusd@trade/'
                          'wtcbtc@trade/wavesusdt@trade/snglsbtc@trade/batbnb@trade/agibtc@trade/databtc@trade/bchusdc@trade/evxbtc@trade/solbnb@trade/stxbtc@trade/batusdc@trade/cdtbtc@trade/arpausdt@trade/'
                          'dockbtc@trade/cvcbtc@trade/fuelbtc@trade/btsusdt@trade/eosbusd@trade/dltbtc@trade/mcousdt@trade/wanusdt@trade/knceth@trade/ltceth@trade/ftmusdt@trade/troyusdt@trade/arpabtc@trade/'
                          'lskbtc@trade/wintrx@trade/iotxeth@trade/powrbtc@trade/usdtrub@trade/grsbtc@trade/tctbtc@trade/bchbnb@trade/btcrub@trade/hotbtc@trade/keyusdt@trade/adausdc@trade/xzcbtc@trade/gxsbtc@trade/'
                          'mtlbtc@trade/dgbbusd@trade/pivxbtc@trade/stratusdt@trade/etheur@trade/tntbtc@trade/maticbnb@trade/adxbtc@trade/vibebtc@trade/stxusdt@trade/navbtc@trade/sysbtc@trade/dcrbtc@trade/'
                          'bnbusdc@trade/mdtusdt@trade/zeceth@trade/mithbtc@trade/qspeth@trade/onebnb@trade/neoeth@trade/cocosusdt@trade/funusdt@trade/aebtc@trade/sntbtc@trade/stptusdt@trade/xmreth@trade/'
                          'adatusd@trade/dockusdt@trade/neblbtc@trade/ethrub@trade/eosusdc@trade/zecbusd@trade/ltcbusd@trade/ltcusdc@trade/fttbnb@trade/duskbtc@trade/datausdt@trade/mblbnb@trade/rcnbtc@trade/'
                          'vetbusd@trade/poebtc@trade/scbnb@trade/npxsusdt@trade/wabibnb@trade/duskusdt@trade/bnteth@trade/ltcbnb@trade/xrpusdc@trade/naseth@trade/ardrbtc@trade/linktusd@trade/bcptbtc@trade/'
                          'dgbbnb@trade/erdbusd@trade/elfeth@trade/ontbusd@trade/vitebtc@trade/gtobtc@trade/mithusdt@trade/nulseth@trade/mcoeth@trade/bttbnb@trade/xmrbnb@trade/xlmeth@trade/algotusd@trade/'
                          'eosbnb@trade/arpabnb@trade/fttusdt@trade/adabnb@trade/winbnb@trade/dntbtc@trade/omgeth@trade/onteth@trade/zectusd@trade/xtzbnb@trade/tomobusd@trade/snmbtc@trade/hcbtc@trade/poabtc@trade/'
                          'tomobnb@trade/thetaeth@trade/bttbusd@trade/nxsbtc@trade/repeth@trade/btcidrt@trade/etcbusd@trade/trxusdc@trade/etceth@trade/cvcusdt@trade/xtzbusd@trade/wtcusdt@trade/xzcusdt@trade/'
                          'npxseth@trade/thetabnb@trade/cdteth@trade/mthbtc@trade/celrbnb@trade/yoyobtc@trade/enjeth@trade/mftusdt@trade/algobnb@trade/xrptusd@trade/evxeth@trade/gtousdt@trade/mtlusdt@trade/'
                          'xlmbusd@trade/hoteth@trade/trxtusd@trade/qlceth@trade/nknbnb@trade/rlceth@trade/stmxeth@trade/nanoeth@trade/hbarbnb@trade/blzbnb@trade/wrxbnb@trade/iosteth@trade/trxxrp@trade/'
                          'lskusdt@trade/ltctusd@trade/atombnb@trade/manaeth@trade/blzeth@trade/tctusdt@trade/vibeth@trade/ctsibnb@trade/stptbtc@trade/hbarbusd@trade/dentusdt@trade/trxbusd@trade/ardrusdt@trade/'
                          'cndbtc@trade/zrxeth@trade/snteth@trade/ltcpax@trade/bntbusd@trade/aioneth@trade/vetbnb@trade/ognbnb@trade/viteusdt@trade/algobusd@trade/brdeth@trade/mdtbnb@trade/mithbnb@trade/'
                          'bandbnb@trade/btttusd@trade/ankrbnb@trade/bcdeth@trade/bgbpusdc@trade/hcusdt@trade/xmrbusd@trade/nebleth@trade/ostbtc@trade/dasheth@trade/iotaeth@trade/chrbnb@trade/rdneth@trade/'
                          'denteth@trade/qkceth@trade/loometh@trade/bnbpax@trade/nanobusd@trade/wprbtc@trade/brdbnb@trade/zenbnb@trade/lrceth@trade/trxpax@trade/qtumbusd@trade/ppteth@trade/waneth@trade/'
                          'gnteth@trade/busdtry@trade/usdcpax@trade/hotbnb@trade/xrppax@trade/zeneth@trade/winusdc@trade/phbtusd@trade/neobnb@trade/cotibnb@trade/rvnbnb@trade/xlmbnb@trade/wtceth@trade/'
                          'rvnbusd@trade/kavabnb@trade/bnbtry@trade/waveseth@trade/cmteth@trade/neobusd@trade/ontbnb@trade/strateth@trade/keyeth@trade/powreth@trade/bnbtusd@trade/neblbnb@trade/qtumeth@trade/'
                          'zecusdc@trade/docketh@trade/perlbnb@trade/bnbngn@trade/usdtidrt@trade/adxeth@trade/lsketh@trade/bnbidrt@trade/funeth@trade/bttusdc@trade/dataeth@trade/enjbusd@trade/chzbnb@trade/'
                          'iqbnb@trade/engeth@trade/bqxeth@trade/dashbusd@trade/stxbnb@trade/iostbnb@trade/zrxbnb@trade/usdctusd@trade/zecbnb@trade/wrxbusd@trade/mfteth@trade/pivxeth@trade/etcbnb@trade/'
                          'wanbnb@trade/icxeth@trade/databusd@trade/grseth@trade/eospax@trade/xrptry@trade/wtcbnb@trade/wavesusdc@trade/gvteth@trade/stratbusd@trade/iotabnb@trade/steembnb@trade/steemeth@trade/'
                          'icxbnb@trade/kmdeth@trade/rlcbnb@trade/neotusd@trade/xzceth@trade/troybnb@trade/oneusdc@trade/storjeth@trade/fetbnb@trade/ftmbnb@trade/beambnb@trade/arneth@trade/btczar@trade/'
                          'ctsibusd@trade/hivebnb@trade/stptbnb@trade/hceth@trade/aionbnb@trade/ethtry@trade/mftbnb@trade/dashbnb@trade/neousdc@trade/xrprub@trade/gxseth@trade/cocosbnb@trade/cvceth@trade/'
                          'xrpeur@trade/icxbusd@trade/bttpax@trade/cosbnb@trade/ncasheth@trade/gtoeth@trade/tnteth@trade/ltobnb@trade/aionbusd@trade/enjbnb@trade/btsbusd@trade/aeeth@trade/xzcbnb@trade/renbnb@trade/'
                          'wavesbnb@trade/wavesbusd@trade/usdtzar@trade/usdsusdt@trade/algopax@trade/gtobnb@trade/mtleth@trade/xemeth@trade/osteth@trade/bnbeur@trade/busdrub@trade/bnbrub@trade',

               'binanceus': 'btcusd@trade/adausd@trade/zilusd@trade/vetusd@trade/usdtusd@trade/ethusd@trade/btcusdt@trade/linkusd@trade/xrpusd@trade/btcbusd@trade/nanousd@trade/enjusd@trade/vetusdt@trade/' \
                            'hbarusd@trade/adausdt@trade/algousd@trade/xtzusd@trade/rvnusd@trade/bnbusd@trade/busdusd@trade/ethusdt@trade/adabtc@trade/zilbusd@trade/icxusd@trade/zrxusd@trade/xlmusd@trade/' \
                            'ethbtc@trade/maticusd@trade/iotausd@trade/zecusd@trade/atomusd@trade/xrpusdt@trade/bchusd@trade/bnbusdt@trade/repusd@trade/ltcusd@trade/ontusd@trade/neousd@trade/xlmusdt@trade/' \
                            'ltcusdt@trade/batusd@trade/bnbbusd@trade/xrpbtc@trade/bnbbtc@trade/wavesusd@trade/etcusd@trade/xtzbtc@trade/omgusd@trade/neousdt@trade/ethbusd@trade/ontusdt@trade/xrpbusd@trade/' \
                            'hbarbusd@trade/bchusdt@trade/dogeusdt@trade/atomusdt@trade/zrxusdt@trade/ltcbtc@trade/dashusd@trade/qtumusd@trade/algobusd@trade/xtzbusd@trade/batusdt@trade/etcusdt@trade/' \
                            'maticbusd@trade/bchbtc@trade/repbusd@trade/qtumusdt@trade',

               'bitfinex': ['BTCUSD', 'ETHUSD', 'BTCUSDt', 'USDtUSD', 'BTCEUR', 'XRPUSD', 'BABUSD', 'EOSUSD', 'ETHEUR', 'LTCUSD', 'BTCGBP', 'ETHBTC', 'BTCJPY', 'XTZUSD', 'BSVBTC', 'ZECUSD',
                            'DGBBTC', 'NEOUSD', 'ETHJPY', 'BABBTC', 'XAUTUSD', 'IOTABTC', 'LTCBTC', 'RBTBTC', 'IOTAUSD', 'XRPBTC', 'XMRUSD', 'TRXUSD', 'BSVUSD', 'ALGOUSD', 'IQXUSD', 'QTUMBTC', 'EOSBTC',
                            'WAXBTC', 'ZRXUSD', 'OMGBTC', 'ETCUSD', 'DAIUSD', 'EOSEUR', 'XMRBTC', 'XTZBTC', 'DASHUSD', 'PAIUSD', 'OMGUSD', 'NEOBTC', 'NECUSD', 'TSDUSD', 'IQXEOS', 'EURSUSD', 'TRXBTC', 'EOSJPY',
                            'LEOUSD', 'AMPLUSDt', 'IOTAEUR', 'UOSUSD', 'ZECBTC', 'XAUTBTC', 'TRXEUR', 'ETCBTC', 'EDOUSD', 'XLMUSD', 'ETHGBP', 'KANUSDt', 'UOSBTC', 'QTUMUSD', 'EOSETH', 'FTTUSD', 'NEOEUR', 'KNCBTC',
                            'EOSUSDt', 'ETPUSD', 'EDOBTC', 'TNBUSD', 'FTTUSDt', 'LEOBTC', 'ZILUSD', 'BTGUSD', 'IOTAGBP', 'AUCUSD', 'LTCUSDt', 'TNBETH', 'ALGOUSDt', 'DGBUSD', 'BATUSD', 'RIFBTC', 'AMPLUSD', 'ETPBTC',
                            'BTTUSD', 'VETUSD', 'BTGBTC', 'EOSGBP', 'DAIBTC', 'VSYBTC', 'VSYUSD', 'GNTBTC', 'XVGBTC', 'TNBBTC', 'GNTUSD', 'DATAUSD', 'LRCBTC', 'MLNUSD', 'XVGUSD', 'MKRBTC', 'AVTUSD', 'MKRETH',
                            'TRXETH', 'BABUSDt', 'LEOUSDt', 'ALGOBTC', 'XLMBTC', 'XLMEUR', 'IOTAETH', 'ANTETH', 'IMPUSD', 'CLOBTC', 'VLDUSD', 'PAXUSD', 'DASHBTC', 'AMPLBTC', 'UTNPUSD', 'FSNUSD', 'DATABTC',
                            'SNGLSUSD', 'REPBTC', 'OMGETH', 'LRCUSD', 'ANTBTC', 'ENJUSD', 'CNDUSD', 'NEOETH', 'WBTCETH', 'WBTCUSD', 'ZCNUSD', 'BTCXCH', 'RBTUSD', 'DUSKBTC', 'ZRXBTC', 'IOTAJPY', 'DATAETH',
                            'BATBTC', 'ZRXETH', 'NEOGBP', 'VETBTC', 'DGXUSD', 'BTTBTC', 'DGXETH', 'MKRUSD', 'DUSKUSD', 'DAIETH', 'MANAUSD', 'IOSTBTC', 'TRXJPY', 'VEEUSD', 'SNTBTC', 'IOSTUSD', 'UFRUSD', 'EDOETH',
                            'RLCBTC', 'OMNUSD', 'XAUTUST', 'KNCUSD', 'NEOJPY', 'UTKUSD', 'PASSUSD', 'AIOBTC', 'ATOUSD', 'XRAUSD', 'NECETH', 'SNTETH', 'TRXGBP', 'UDCUSD', 'GSDUSD', 'SANUSD', 'REQUSD', 'XCHFETH',
                            'WPRUSD', 'MANABTC', 'SANETH', 'ABYSSUSD', 'CSUSD', 'WAXUSD', 'PNKETH', 'AIOUSD', 'WLOUSD', 'ONLUSD', 'FUNUSD', 'ELFUSD', 'XCHFUSD', 'FUNETH', 'REPUSD', 'RLCUSD', 'LOOMUSD', 'FOAMUSD',
                            'ODEUSD', 'AGIUSD', 'CBTUSD', 'WTCUSD', 'OKBUSD', 'YOYOWUSD', 'RDNUSD', 'LEOETH', 'PNKUSD', 'GOTETH', 'GENUSD', 'IOSTETH', 'MGOUSD', 'MTNUSD', 'ANTUSD', 'ETPETH', 'LEOEOS', 'BFTUSD',
                            'GNTETH', 'MITHUSD', 'CLOUSD', 'CNNUSD', 'QASHUSD', 'ORSUSD', 'REPETH', 'DTAUSD', 'ESSUSD', 'BFTBTC', 'AIDUSD', 'OKBUSDt', 'ODEBTC', 'SPANKUSD', 'CTXCUSD', 'BNTUSD', 'OMNBTC', 'DTHUSD',
                            'NECBTC', 'BOXUSD', 'ASTUSD', 'RIFUSD', 'SEERUSD', 'STORJUSD', 'POLYUSD', 'RCNUSD', 'SANBTC', 'HOTUSD', 'TRIOUSD', 'ATOBTC', 'SNTUSD', 'GNOUSD', 'GOTUSD', 'ODEETH', 'MANUSD', 'XLMETH',
                            'DRGNUSD', 'DTUSD', 'OKBBTC', 'ATMIUSD', 'BATETH', 'CNDETH', 'XLMGBP', 'ATOETH', 'TKNUSD', 'INTUSD', 'USDKUSDt', 'LYMUSD', 'USDKETH', 'NCASHUSD', 'POAUSD', 'USDKBTC', 'SWMUSD',
                            'USDKUSD', 'USDKEOS', 'KANUSD', 'YEEDUSD', 'RTEUSD', 'ZBTUSD', 'GOTEUR'],

               'bitflyer': ['BTC_JPY', 'ETH_JPY', 'BTC_USD', 'BTC_EUR', 'ETH_BTC'],

               'bitforex': ['usdt-btc', 'usdt-ltc', 'usdt-eth', 'eth-xlm', 'usdt-neo', 'usdt-xlm', 'usdt-bch', 'usdt-fil', 'btc-eth', 'btc-eos', 'eth-beam', 'usdt-bsv', 'btc-atom', 'eth-yo', 'btc-link', 'eth-cnrg',
                            'btc-xlm', 'usdt-dash', 'btc-xzc', 'btc-yo', 'btc-dash', 'usdt-gusd', 'btc-xtz', 'btc-bsv', 'usdt-beam', 'btc-eved', 'btc-xrp', 'btc-bch', 'btc-trx', 'btc-kicks', 'usdt-dot', 'eth-dash',
                            'eth-atom', 'eth-eos', 'usdt-elama', 'eth-tomo', 'btc-mwc', 'btc-zel', 'usdt-grin', 'usdt-gold', 'eth-neo', 'eth-bdp', 'btc-gold', 'eth-qtum', 'usdt-eos', 'usdt-mwc', 'eth-mwc',
                            'usdt-qtum', 'usdt-xrp', 'btc-zec', 'eth-bf', 'usdt-abbc', 'eth-xzc', 'eth-link', 'usdt-tpay', 'eth-ht', 'btc-abbc', 'btc-beam', 'eth-abl', 'btc-elama', 'eth-gold', 'btc-grin',
                            'btc-tomo', 'usdt-omg', 'usdt-mhc', 'btc-noiz', 'usdt-etc', 'usdt-atom', 'eth-xtz', 'usdt-ckb', 'usdt-bdp', 'eth-mhc', 'btc-rvn', 'eth-adn', 'btc-bnb', 'eth-hqx', 'usdt-trx', 'btc-ht',
                            'usdt-doge', 'btc-brz', 'eth-ecom', 'eth-doge', 'eth-zec', 'usdt-geo', 'usdt-kbc', 'usdt-bpx', 'usdt-mgo', 'btc-tpay', 'eth-eved', 'btc-bos', 'usdt-pla', 'eth-bwxx', 'usdt-iq', 'btc-iq',
                            'usdt-ecom', 'btc-mhc', 'eth-kbc', 'eth-got', 'btc-fto', 'usdt-qqq', 'btc-roobee', 'eth-kicks', 'usdt-bf', 'btc-bdp', 'eth-ely', 'eth-bpx', 'eth-ubex', 'eth-dav', 'btc-kbc', 'eth-xrp',
                            'usdt-tusd', 'usdt-isr', 'btc-vsys', 'usdt-matic', 'btc-gap', 'btc-matic', 'eth-zlw', 'eth-datx', 'eth-isr', 'eth-hydro', 'eth-edr', 'usdt-ode', 'usdt-zlw', 'usdt-btt', 'usdt-rev',
                            'eth-fund', 'usdt-fund', 'usdt-bos', 'btc-zlw', 'usdt-elf', 'usdt-abyss', 'btc-fund', 'btc-hmq', 'usdt-datx', 'usdt-solo', 'eth-mir', 'usdt-ubex', 'eth-zel', 'eth-bnb', 'usdt-ctxc',
                            'usdt-nobs', 'btc-blood', 'usdt-dws', 'usdt-credit', 'eth-dws', 'btc-wiken', 'eth-dxt', 'btc-e2c', 'eth-clo', 'usdt-mir', 'usdt-crn', 'usdt-e2c', 'usdt-imt', 'usdt-acdc', 'usdt-kin',
                            'eth-credit', 'usdt-plc', 'eth-gap', 'usdt-plat', 'eth-nobs', 'btc-plc', 'eth-dacc', 'eth-mb', 'usdt-mith', 'btc-tosc', 'btc-mb'],

               'bittrex': ['BTC-CRO', 'USDT-CRO', 'USD-BTC', 'USDT-BTC', 'BTC-DOGE', 'BTC-ETH', 'BTC-ADA', 'BTC-SXP', 'BTC-BSV', 'BTC-DGB', 'BTC-LINK', 'USDT-MOF', 'BTC-XLM', 'BTC-DEP', 'USDT-DEP', 'BTC-XEM',
                           'USDT-XRP', 'BTC-XRP', 'USD-LINK', 'BTC-STRAT', 'BTC-RLC', 'BTC-LBC', 'BTC-WAXP', 'USD-ETH', 'USD-USDT', 'USD-BSV', 'BTC-XHV', 'BTC-TRX', 'BTC-OCEAN', 'BTC-MOF', 'BTC-AKRO', 'BTC-LUNA',
                           'BTC-MET', 'USDT-BSV', 'BTC-VLX', 'USD-ADA', 'BTC-ABBC', 'BTC-VET', 'BTC-TUSD', 'USD-WAXP', 'BTC-XTZ', 'USDT-ETH', 'BTC-KMD', 'USDT-WAXP', 'BTC-LTC', 'USD-XRP', 'BTC-XVG', 'EUR-BSV',
                           'BTC-ENJ', 'USDT-LUNA', 'USD-XTZ', 'BTC-XTP', 'USDT-VLX', 'EUR-BTC', 'USDT-LBC', 'BTC-RVN', 'BTC-SYS', 'BTC-TRAC', 'BTC-UBT', 'USDT-XUC', 'BTC-BAT', 'BTC-ATOM', 'USDT-BOA', 'USDT-REV',
                           'BTC-XUC', 'USDT-XLM', 'BTC-SC', 'BTC-ZIL', 'BTC-ARK', 'BTC-SOLVE', 'BTC-QNT', 'BTC-ZEN', 'USDT-DGB', 'BTC-HEDG', 'USD-HBAR', 'USDT-LINK', 'BTC-CKB', 'BTC-BURST', 'USDT-BAT', 'USD-DGB',
                           'BTC-XMR', 'BTC-ZRX', 'USDT-DOGE', 'USDT-XTZ', 'USDT-ADA', 'USD-BAT', 'BTC-WAVES', 'ETH-UBT', 'BTC-XZC', 'BTC-USDC', 'BTC-DMT', 'ETH-LINK', 'BTC-DAI', 'BTC-OMG', 'BTC-GNO', 'BTC-ALGO',
                           'USDT-DNA', 'ETH-WAXP', 'BTC-NEO', 'ETH-GNO', 'ETH-XTZ', 'ETH-ADA', 'USDT-KDAG', 'BTC-BCH', 'USD-DOGE', 'USDT-GXC', 'USD-ATOM', 'USDT-NEO', 'BTC-HBAR', 'BTC-VTC', 'ETH-DGB', 'USDT-ATOM',
                           'BTC-DASH', 'BTC-GNT', 'USDT-UCT', 'USD-ZEN', 'USDT-ZRX', 'BTC-ZEC', 'BTC-ETC', 'USD-LTC', 'BTC-MANA', 'USDT-XVG', 'USDT-LTC', 'USDT-DAI', 'BTC-NMR', 'BTC-SIX', 'USDT-ENJ', 'BTC-MFT',
                           'BTC-OGN', 'BTC-RDD', 'ETH-ANT', 'USDT-CELO', 'BTC-ANT', 'BTC-MAID', 'BTC-GBYTE', 'BTC-STEEM', 'BTC-QTUM', 'USD-ZRX', 'BTC-BNT', 'ETH-ZEC', 'BTC-VRA', 'BTC-TUBE', 'ETH-SC', 'USD-ENJ',
                           'BTC-HIVE', 'BTC-CVC', 'BTC-REP', 'BTC-ONT', 'BTC-PXL', 'BTC-GAME', 'USDT-HDAO', 'BTC-DCR', 'BTC-ARDR', 'BTC-OXT', 'BTC-LUCY', 'BTC-HDAO', 'BTC-CELO', 'USDT-VET', 'ETH-MET', 'BTC-EOS',
                           'USDT-NMR', 'USDT-LUCY', 'ETH-XRP', 'USDT-OMG', 'BTC-LOOM', 'USDT-EOS', 'BTC-UCT', 'USDT-WICC', 'USDT-TUSD', 'USD-DAI', 'BTC-STC', 'USD-BCH', 'BTC-BTM', 'USD-ZEC', 'BTC-LBA', 'ETH-BAT',
                           'USD-EOS', 'BTC-UTK', 'ETH-HBAR', 'ETH-XLM', 'USDT-USDC', 'BTC-ELAMA', 'BTC-LSK', 'ETH-NEO', 'ETH-ATOM', 'USDT-OCEAN', 'ETH-ZRX', ' PepeCoin-Memetic ', 'BTC-MEME', 'USDT-TRX', 'BTC-ICX',
                           'BTC-FCT', 'USDT-RVN', 'USDT-OXT', 'BTC-PART', 'BTC-BLOCK', 'BTC-MONA', 'ETH-XEM', 'BTC-AR', 'BTC-ENG', 'BTC-UBQ', 'USDT-ETC', 'USDT-DASH', 'USDT-HBAR', 'BTC-LAMB', 'USDT-KDA', 'EUR-USDT',
                           'ETH-BCH', 'BTC-COMP', 'BTC-MTL', 'USD-KMD', 'USD-DCR', 'USD-SC', 'USDT-ZEC', 'USD-USDC', 'ETH-GNT', 'BTC-QRL', 'BTC-GXC', 'BTC-FSN', 'ETH-TRX', 'BTC-EXP', 'USD-ALGO', 'BTC-XST',
                           'ETH-DASH', 'BTC-BTS', 'USDT-BCH', 'BTC-IRIS', 'BTC-XDN', 'BTC-TNC', 'BTC-MCO', 'BTC-EDG', 'BTC-PHNX', 'BTC-DUSK', 'BTC-PAY', 'BTC-CTC', 'ETH-NPXS', 'BTC-SNT', 'ETH-XMR', 'ETH-BSV',
                           'ETH-STRAT', 'BTC-NKN', 'USD-SOLVE', 'BTC-ELF', 'BTC-GO', 'USD-ETC', 'BTC-RCN', 'USDT-CKB', 'BTC-SPND', 'BTC-KDA', 'USD-TUSD', 'USDT-ALGO', 'BTC-DRGN', 'USDT-SC', 'USD-RVN', 'BTC-BWX',
                           'BTC-FX', 'USD-CELO', 'BTC-HNS', 'ETH-DOGE', 'BTC-APIX', 'USDT-XMR', 'BTC-FXC', 'USD-TRX', 'BTC-NXS', 'BTC-AEON', 'BTC-LRC', 'USD-DASH', 'BTC-OK', 'USDT-COMP', 'BTC-UKG', 'BTC-EDR',
                           'BTC-BTU', 'ETH-DAI', 'BTC-PIVX', 'ETH-ENJ', 'BTC-ANKR', 'BTC-DCT', 'BTC-APM', 'O Coin-I', 'BTC-IOC', 'USDT-SOLVE', 'USDT-BTT', 'ETH-NMR', 'BTC-MRPH', 'BTC-BTT', 'BTC-IOTX', 'BTC-PROM',
                           'BTC-HBD', 'BTC-PAX', 'BTC-VIA', 'BTC-RADS', 'USD-COMP', 'BTC-CHR', 'BTC-REV', 'BTC-MUE', 'BTC-MER', 'EUR-ETH', 'BTC-ABYSS', 'BTC-NLG', 'BTC-WINGS', 'BTC-NAV', 'BTC-VANY', 'ETH-WAVES',
                           'ETH-MANA', 'BTC-POWR', 'BTC-CPC', 'USDT-PMA', 'BTC-NXT', 'ETH-CVC', 'BTC-ONG', 'BTC-EXCL', 'BTC-IOST', 'BTC-POT', 'BTC-STPT', 'BTC-BOA', 'ETH-LTC', 'BTC-PPC', 'BTC-VEE', 'BTC-STMX',
                           'BTC-PINK', 'BTC-STORJ', 'ETH-OMG', 'ETH-UKG', 'BTC-BLOC', 'BTC-GRS', 'BTC-NPXS', 'ETH-ETC', 'BTC-EMC2', 'BTC-VRC', 'BTC-HYDRO', 'BTC-SPHR', 'BTC-FLO', 'BTC-IOTA', 'BTC-GRIN', 'ETH-SOLVE',
                           'BTC-CND', 'BTC-SPC', 'BTC-ORBS', 'ETH-EOS', 'USDT-HNS', 'BTC-IGNIS', 'ETH-MCO', 'BTC-SRN', 'ETH-CELO', 'ETH-OGN', 'USDT-ONT', 'BTC-RFR', 'USDT-TRAC', 'ETH-ENG', 'USDT-UQC', 'BTC-VBK',
                           'ETH-COMP', 'BTC-DNA', 'USDT-GRIN', 'BTC-HDAC', 'BTC-DNT', 'USDT-HXRO', 'BTC-VITE', 'BTC-FTC', 'BTC-ART', 'BTC-DENT', 'BTC-XMY', 'ETH-FX', 'BTC-PAL', 'BTC-PMA', 'BTC-CMCT', 'BTC-GEO',
                           'BTC-CRW', 'BTC-BLK', 'BTC-UQC', 'BTC-SBD', 'BTC-NLC2', 'BTC-PTOY', 'ETH-REP', 'USDT-DCR', 'BTC-HXRO', 'ETH-USDC', 'BTC-ADX', 'USDT-MDT', 'BTC-HYC', 'BTC-HMQ', 'BTC-SIB', 'BTC-CURE',
                           'BTC-XSR', 'ETH-HNS', 'BTC-MDT', 'BTC-WICC', 'USDT-APM', 'BTC-CTXC', 'USD-HIVE', 'BTC-ADT', 'ETH-VIB', 'BTC-DAWN', 'BTC-OST', 'BTC-VIB', 'EUR-TRX', 'BTC-URAC', 'BTC-FNB', 'USDT-HIVE',
                           'BTC-INCNT', 'BTC-ION', 'ETH-PAY'],

               'biki': ['btcusdt', 'ltcusdt', 'ethusdt', 'xlmeth', 'neousdt', 'xlmusdt', 'bchusdt', 'filusdt', 'ethbtc', 'eosbtc', 'beameth', 'bsvusdt', 'atombtc', 'yoeth', 'linkbtc', 'cnrgeth', 'xlmbtc',
                        'dashusdt', 'xzcbtc', 'yobtc', 'dashbtc', 'gusdusdt', 'xtzbtc', 'bsvbtc', 'beamusdt', 'bnbeth', 'evedbtc', 'xrpbtc', 'bchbtc', 'trxbtc', 'kicksbtc', 'dotusdt', 'dasheth', 'atometh',
                        'elamausdt', 'eoseth', 'tomoeth', 'mwcbtc', 'zelbtc', 'grinusdt', 'goldusdt', 'neoeth', 'bdpeth', 'goldbtc', 'qtumeth', 'mwcusdt', 'eosusdt', 'mwceth', 'qtumusdt', 'xrpusdt', 'zecbtc',
                        'bfeth', 'abbcusdt', 'tpayusdt', 'linketh', 'xzceth', 'hteth', 'abbcbtc', 'beambtc', 'ableth', 'elamabtc', 'goldeth', 'grinbtc', 'tomobtc', 'omgusdt', 'mhcusdt', 'etcusdt', 'noizbtc',
                        'atomusdt', 'xtzeth', 'ckbusdt', 'bdpusdt', 'mhceth', 'rvnbtc', 'adneth', 'bnbbtc', 'trxusdt', 'hqxeth', 'htbtc', 'dogeusdt', 'brzbtc', 'ecometh', 'dogeeth', 'mithusdt', 'zeceth', 'gapeth',
                        'geousdt', 'kbcusdt', 'bpxusdt', 'mgousdt', 'tpaybtc', 'evedeth', 'bosbtc', 'plausdt', 'bwxxeth', 'iqusdt', 'iqbtc', 'ecomusdt', 'mhcbtc', 'kbceth', 'ftobtc', 'goteth', 'qqqusdt', 'roobeebtc',
                        'kickseth', 'bfusdt', 'bdpbtc', 'elyeth', 'bpxeth', 'ubexeth', 'daveth', 'kbcbtc', 'xrpeth', 'tusdusdt', 'isrusdt', 'vsysbtc', 'maticusdt', 'gapbtc', 'maticbtc', 'zlweth', 'hydroeth',
                        'isreth', 'datxeth', 'edreth', 'odeusdt', 'zlwusdt', 'bttusdt', 'revusdt', 'fundeth', 'fundusdt', 'zlwbtc', 'bosusdt', 'elfusdt', 'abyssusdt', 'fundbtc', 'hmqbtc', 'datxusdt', 'solousdt',
                        'mireth', 'ubexusdt', 'zeleth', 'ctxcusdt', 'nobsusdt', 'bloodbtc', 'dwsusdt', 'creditusdt', 'dwseth', 'wikenbtc', 'dxteth', 'e2cbtc', 'cloeth', 'mirusdt', 'crnusdt', 'e2cusdt', 'imtusdt',
                        'acdcusdt', 'kinusdt', 'crediteth', 'mbeth', 'plcusdt', 'platusdt', 'nobseth', 'plcbtc', 'dacceth', 'toscbtc', 'mbbtc'],

               'bitmex': 'trade:XBTUSD,trade:ETHUSD,trade:XRPUSD',

               'bitstamp': ['btcusd', 'xrpusd', 'btceur', 'ethusd', 'etheur', 'bchusd', 'ltcusd', 'xrpeur', 'btcgbp', 'ethbtc', 'bcheur', 'xlmbtc', 'ltceur', 'xlmeur', 'xrpbtc', 'ltcbtc', 'bchbtc', 'xlmusd',
                            'ethgbp', 'xrpgbp', 'ltcgbp', 'xlmgbp', 'paxusd', 'bchgbp', 'btcpax', 'ethpax', 'paxeur', 'paxgbp', 'xrppax'],

               'coinbase': ['BTC-USD', 'ETH-USD', 'BTC-EUR', 'LINK-USD', 'BTC-GBP', 'KNC-USD', 'XRP-USD', 'OMG-USD', 'ETH-EUR', 'ETH-BTC', 'BCH-USD', 'BTC-USDC', 'LTC-USD', 'OXT-USD', 'XTZ-USD', 'ETH-USDC',
                            'BAT-USDC', 'MKR-USD', 'ZRX-USD', 'XLM-USD', 'REP-USD', 'ETH-GBP', 'OMG-EUR', 'EOS-USD', 'KNC-BTC', 'XRP-EUR', 'ETC-USD', 'OMG-GBP', 'XRP-BTC', 'OMG-BTC', 'ZRX-BTC', 'ALGO-USD',
                            'DAI-USD', 'LINK-ETH', 'MKR-BTC', 'ATOM-USD', 'XTZ-BTC', 'DAI-USDC', 'BCH-BTC', 'ZRX-EUR', 'ZEC-USDC', 'BAT-ETH', 'LTC-BTC', 'BCH-EUR', 'ATOM-BTC', 'LTC-EUR', 'LTC-GBP', 'XLM-BTC',
                            'DASH-USD', 'REP-BTC', 'ETH-DAI', 'XLM-EUR', 'EOS-BTC', 'EOS-EUR', 'BCH-GBP', 'ZEC-BTC', 'ETC-EUR', 'ETC-GBP', 'ETC-BTC', 'DASH-BTC', 'GNT-USDC', 'CVC-USDC', 'MANA-USDC', 'LOOM-USDC',
                            'DNT-USDC'],

               'coinex': ['BTCUSDT', 'BSVBTC', 'ETHBTC', 'BSVUSDT', 'BCHBTC', 'ETHUSDT', 'ETCBTC', 'BSVBCH', 'BCHUSDT', 'ETHBCH', 'ETCUSDT', 'ETCBCH', 'BTCUSDC', 'EOSBTC', 'LTCUSDT', 'BTCPAX', 'DASHBTC',
                          'BTCTUSD', 'XRPUSDT', 'LTCBTC', 'EOSUSDT', 'ATOMBTC', 'ZECUSDT', 'EOSETH', 'XMRUSDT', 'ZECBTC', 'DASHBCH', 'TRXBTC', 'DASHUSDT', 'EOSBCH', 'XRPBTC', 'TRXUSDT', 'BATBTC', 'NEOUSDT',
                          'XMRBTC', 'DOGEBTC', 'ADABTC', 'ATOMBCH', 'DOGEUSDT', 'ADAUSDT', 'BTTBTC', 'STORJUSDT', 'BTTUSDT', 'BATETH', 'OKBUSDT', 'NEOBTC', 'ETHUSDC', 'LTCBCH', 'TRXETH', 'LINKBTC', 'ZILUSDT',
                          'ETHPAX', 'TRXBCH', 'BATBCH', 'ZILBTC', 'KSMBTC', 'ETHTUSD', 'ONTBTC', 'BCHUSDC', 'DOGEBCH', 'OKBBTC', 'ONTUSDT', 'LINKETH', 'BCHPAX', 'STORJBTC', 'BTTBCH', 'BCHTUSD', 'ADABCH',
                          'BATUSDT', 'LTCUSDC', 'ALGOBTC', 'XLMUSDT', 'LINKUSDT', 'BNBBTC', 'LINKBCH', 'ATOMUSDT', 'ZILETH', 'SNXUSDT', 'XLMBTC', 'BSVUSDC', 'FTTBTC', 'ZECBCH', 'DCRBTC', 'XRPBCH', 'DGBBTC',
                          'DCRUSDT', 'OMGBTC', 'ICXBTC', 'CHZUSDT', 'DGBUSDT', 'CETBTC', 'CETUSDT', 'HTBTC', 'BEAMBTC', 'ALGOBCH', 'SNXBTC', 'MANAUSDT', 'KMDBTC', 'XMRBCH', 'ICXUSDT', 'OMGUSDT', 'ALGOUSDT',
                          'BTMUSDT', 'ZILBCH', 'DCRBCH', 'KMDBCH', 'HTUSDT', 'DGBBCH', 'XTZUSDT', 'CKBBTC', 'QTUMUSDT', 'CHZBTC', 'ICXBCH', 'NEOBCH', 'OMGETH', 'ONTBCH', 'AEBTC', 'TCTBTC', 'IOTABTC', 'BEAMUSDT',
                          'SYSBTC', 'IOSTBTC', 'HBARUSDT', 'ACMBTC', 'FCHBTC', 'REPUSDT', 'CETBCH', 'NNBUSDT', 'KDABTC', 'QTUMBTC', 'NNBCET', 'BTMETH', 'LAMBBTC', 'XEMUSDT', 'XTZBTC', 'HOTBTC', 'CNNBTC', 'BTMBTC',
                          'SCUSDT', 'LSKUSDT', 'ZRXUSDT', 'WINGSBTC', 'USDCUSDT', 'HBARBTC', 'XRPUSDC', 'DEROBTC', 'GRINBTC', 'BTMBCH', 'HCUSDT', 'CETETH', 'HOTUSDT', 'BNBUSDT', 'PAXUSDT', 'LSKBTC', 'VETBTC',
                          'TUSDUSDT', 'DEROUSDT', 'VETUSDT', 'VTHOETH', 'CTXCBTC', 'CKBUSDT', 'GRINUSDT', 'ARDRUSDT', 'AEBCH', 'ZRXBTC', 'GUSDUSDT', 'XLMBCH', 'IOTAUSDT', 'ENGBTC', 'RVNBTC', 'XVGBTC', 'IOTABCH',
                          'RVNUSDT', 'GNTBTC', 'NNBBTC', 'XEMBTC', 'FCHBCH', 'REPBTC', 'HOTETH', 'CETUSDC', 'IOSTBCH', 'ELABTC', 'POWRUSDT', 'AEUSDT', 'OMGBCH', 'LBCBTC', 'CTXCUSDT', 'EOSCBTC', 'HYDROETH',
                          'SCBTC', 'HOTBCH', 'GNTUSDT', 'KNCBTC', 'SPICEBCH', 'KSMUSDT', 'GRINBCH', 'POWRBTC', 'ENJBTC', 'DEROBCH', 'EGTBTC', 'LAMBUSDT', 'IOSTUSDT', 'GNTETH', 'VETETH', 'ARDRBTC', 'HCBCH',
                          'XZCUSDT', 'KANBTC', 'XZCBTC', 'HCBTC', 'HNSUSDT', 'ELAUSDT', 'ENGUSDT', 'MANABTC', 'TCTETH', 'ARDRBCH', 'NRGBTC', 'VSYSUSDT', 'CMTUSDT', 'ELABCH', 'KNCUSDT', 'OXTUSDT', 'XTZBCH',
                          'ENJUSDT', 'CMTBTC', 'SIPCUSDT', 'SPOKBTC', 'ZRXETH', 'MATICUSDT', 'XVGBCH', 'HNSBTC', 'LOOMUSDT', 'FTTUSDT', 'SPICECET', 'VETBCH', 'WAVESUSDT', 'VSYSBTC', 'NRGUSDT', 'GASBTC',
                          'MATICBTC', 'ZENBTC', 'SPOKUSDT', 'WAVESBTC', 'LOOMBTC', 'RVNBCH', 'ZENUSDT', 'QTUMBCH', 'LAMBETH', 'SYSBCH', 'TRTLBCH', 'MKRBTC', 'PGNUSDT', 'MKRUSDT', 'ZRXBCH', 'XZCBCH', 'NANOBTC',
                          'ULTBTC', 'LSKBCH', 'XEMBCH', 'OXTBTC', 'EMCBTC', 'SUMOBTC', 'ONGBTC', 'ARRRBTC', 'NANOUSDT', 'ANTUSDT', 'ANTBTC', 'ZERBTC', 'SCBCH', 'FCHUSDT', 'VSYSBCH', 'ACMUSDT', 'AYAUSDT', 'KDAUSDT',
                          'PGNBTC', 'BCNUSDT', 'HYDROBTC', 'EOSCUSDT', 'NANOBCH', 'SEROBTC', 'SNTUSDT', 'LOOMETH', 'WAVESBCH', 'OLTBTC', 'ZERUSDT', 'BCNBTC', 'DAIUSDT', 'ULTETH', 'AYABTC', 'EMCUSDT', 'SNTBTC',
                          'LBCUSDT', 'TRTLBTC'],

               'gate': ['BTC_USDT', 'ETH_USDT', 'EOS_USDT', 'BCHSV_USDT', 'MBL_USDT', 'VIDY_USDT', 'BCH_USDT', 'LTC_USDT', 'GT_USDT', 'SERO_USDT', 'ONT_USDT', 'FTI_USDT', 'FIL_USDT', 'ZIL_USDT', 'MDA_USDT',
                        'RVC_USDT', 'ZEC_USDT', 'BEAM_USDT', 'XRP_USDT', 'BTM_USDT', 'ATP_USDT', 'GRIN_USDT', 'COS_USDT', 'KAI_USDT', 'BCD_USDT', 'AE_USDT', 'ADA_USDT', 'TFUEL_USDT', 'HT_USDT', 'ETC_USDT',
                        'XTZ_USDT', 'LEND_USDT', 'GTC_USDT', 'LRC_USDT', 'KNC_USDT', 'TRX_USDT', 'OMG_USDT', 'ALGO_USDT', 'ETH_BTC', 'OCN_USDT', 'LYM_USDT', 'STORJ_USDT', 'MXC_USDT', 'VET_USDT', 'NAS_USDT',
                        'GXS_USDT', 'RVN_USDT', 'LINK_USDT', 'CKB_USDT', 'ARPA_USDT', 'XTZ_BTC', 'DASH_USDT', 'DOGE_USDT', 'BNB_USDT', 'WICC_USDT', 'EOSBULL_USDT', 'KAVA_USDT', 'REM_USDT', 'IOTX_ETH', 'BCHSV_BTC',
                        'THETA_USDT', 'GT_BTC', 'LAMB_USDT', 'DBC_USDT', 'ZRX_USDT', 'BCH_BTC', 'KLAY_USDT', 'ATOM_USDT', 'ZSC_USDT', 'DX_USDT', 'BEAM_BTC', 'EOS_BTC', 'XVG_USDT', 'HC_USDT', 'SNET_USDT',
                        'BLZ_USDT', 'NKN_USDT', 'HNS_USDT', 'QTUM_USDT', 'OKB_USDT', 'BTT_USDT', 'MBL_ETH', 'BAT_USDT', 'REM_ETH', 'MAN_USDT', 'ETC_BTC', 'ELF_USDT', 'XMR_USDT', 'GRIN_BTC', 'EOS_ETH',
                        'QKC_USDT', 'CNNS_USDT', 'DILI_USDT', 'MDT_USDT', 'HBAR_USDT', 'BTS_USDT', 'SNT_USDT', 'DDD_USDT', 'BU_USDT', 'IHT_USDT', 'USDC_USDT', 'ANKR_USDT', 'PAY_USDT', 'HIVE_USDT', 'DATA_USDT',
                        'GNX_USDT', 'ZSC_ETH', 'LTC_BTC', 'SENC_USDT', 'BTC_USDC', 'MIX_USDT', 'CELR_USDT', 'COTI_USDT', 'OMG_BTC', 'DOGE_BTC', 'LYM_BTC', 'MANA_ETH', 'DREP_USDT', 'OMG_ETH', 'GRIN_ETH', 'QKC_ETH',
                        'AE_BTC', 'HIT_USDT', 'STORJ_BTC', 'LEO_USDT', 'ONG_USDT', 'XVG_BTC', 'QASH_USDT', 'SOP_USDT', 'XLM_USDT', 'TNT_USDT', 'NEO_USDT', 'MANA_USDT', 'MDT_BTC', 'BTO_USDT', 'ZRX_BTC', 'GXS_BTC',
                        'IOTX_USDT', 'RDN_USDT', 'BU_ETH', 'GTC_BTC', 'QBT_USDT', 'FTM_USDT', 'ATOM_BTC', 'GSE_USDT', 'ELEC_USDT', 'ETC_ETH', 'AE_ETH', 'MTV_USDT', 'MKR_USDT', 'TCT_USDT', 'ABT_USDT', 'JNT_USDT',
                        'GMAT_USDT', 'ETHBEAR_USDT', 'KGC_USDT', 'GARD_USDT', 'ZEC_BTC', 'ETHBULL_USDT', 'PI_USDT', 'GNT_USDT', 'MET_USDT', 'BCD_BTC', 'LBK_USDT', 'SKM_USDT', 'BTM_BTC', 'RSR_USDT', 'LRC_ETH',
                        'HAV_USDT', 'HNS_BTC', 'NEO_BTC', 'BAT_BTC', 'TNC_USDT', 'CKB_BTC', 'QKC_BTC', 'RUFF_USDT', 'BNTY_USDT', 'DPY_USDT', 'REP_ETH', 'GAS_USDT', 'FTI_ETH', 'CRO_USDT', 'QASH_BTC', 'RFR_USDT',
                        'BCDN_USDT', 'MCO_ETH', 'ZRX_ETH', 'XRP_BTC', 'LRN_USDT', 'PST_USDT', 'MITH_USDT', 'STEEM_USDT', 'WAVES_USDT', 'DATA_ETH', 'BU_BTC', 'LBA_USDT', 'LYM_ETH', 'MDT_ETH', 'IOTA_USDT',
                        'SMT_USDT', 'SBTC_USDT', 'ICX_USDT', 'XTZ_ETH', 'CVC_USDT', 'CKB_ETH', 'GTC_ETH', 'MTN_USDT', 'XEM_USDT', 'LRC_BTC', 'POWR_BTC', 'TUSD_USDT', 'TOMO_USDT', 'ONE_USDT', 'DASH_BTC', 'SNT_ETH',
                        'MXC_BTC', 'ELF_ETH', 'BEAM_ETH', 'ZIL_ETH', 'RLC_USDT', 'DBC_BTC', 'ADA_BTC', 'LEND_ETH', 'TSL_USDT', 'MDS_USDT', 'ONT_ETH', 'LSK_USDT', 'VET_ETH', 'LEMO_USDT', 'BTS_BTC', 'PAX_USDT',
                        'LSK_BTC', 'SNT_BTC', 'SENC_ETH', 'SWTH_USDT', 'RCN_USDT', 'HSC_USDT', 'VIDY_ETH', 'XEM_BTC', 'DRGN_USDT', 'MOBI_USDT', 'QASH_ETH', 'KNC_ETH', 'BTT_ETH', 'NAS_BTC', 'FUEL_USDT', 'TFUEL_ETH',
                        'EOSDAC_USDT', 'QTUM_BTC', 'CS_USDT', 'DADI_USDT', 'HC_BTC', 'RLC_ETH', 'IOTA_BTC', 'TCT_ETH', 'BCX_USDT', 'PST_ETH', 'REQ_USDT', 'GOD_USDT', 'BCN_USDT', 'DREP_ETH', 'GEM_USDT', 'XMR_BTC',
                        'XMC_USDT', 'DCR_USDT', 'XLM_BTC', 'MCO_USDT', 'BCN_BTC', 'CDT_USDT', 'DCR_BTC', 'WAVES_BTC', 'QSP_USDT', 'RED_USDT', 'JNT_BTC', 'NBOT_USDT', 'BIFI_USDT', 'OAX_USDT', 'XEM_ETH', 'TIPS_ETH',
                        'THETA_ETH', 'BTMX_USDT', 'GMAT_ETH', 'TRX_ETH', 'XRPBULL_USDT', 'QLC_USDT', 'NAS_ETH', 'ICX_ETH', 'GNT_ETH', 'CS_ETH', 'MED_USDT', 'ABT_ETH', 'XLM_ETH', 'DX_ETH', 'RUFF_ETH', 'BLZ_ETH',
                        'EOSBEAR_USDT', 'QSP_ETH', 'HAV_ETH', 'OAX_BTC', 'MDA_ETH', 'BAT_ETH', 'DOCK_USDT', 'POWR_USDT', 'RATING_USDT', 'NANO_USDT', 'VTHO_ETH', 'CDT_ETH', 'RDN_ETH', 'STORJ_ETH', 'IHT_ETH',
                        'LEMO_ETH', 'GAS_BTC', 'RFR_ETH', 'JNT_ETH', 'BNT_ETH', 'QLC_BTC', 'OCN_BTC', 'NANO_BTC', 'QTUM_ETH', 'MXC_ETH', 'GNX_ETH', 'SALT_USDT', 'GEM_ETH', 'QBT_ETH', 'DRGN_ETH', 'LRN_ETH',
                        'COFI_USDT', 'MITH_ETH', 'CNNS_ETH', 'BTG_USDT', 'BTM_ETH', 'OCN_ETH', 'EOSDAC_ETH', 'TNC_BTC', 'TOMO_ETH', 'LINK_ETH', 'BXC_USDT', 'ATP_ETH', 'OPEN_USDT', 'OPEN_ETH', 'DBC_ETH', 'FUEL_ETH',
                        'MED_ETH', 'HSC_ETH', 'MOBI_BTC', 'TNC_ETH', 'SBTC_BTC', 'BTC_PAX', 'MOBI_ETH', 'BTO_ETH', 'QLC_ETH', 'BCX_BTC', 'QBT_QTUM', 'INK_QTUM', 'SNET_ETH', 'GSE_ETH', 'MAN_ETH', 'WINGS_ETH',
                        'BTG_BTC', 'OAX_ETH', 'SWTH_ETH', 'DNT_ETH', 'INK_BTC', 'BXC_ETH', 'RUFF_BTC', 'GOD_BTC', 'MKR_ETH', 'ARN_ETH', 'MTN_ETH', 'DDD_BTC', 'OST_USDT', 'LUN_USDT', 'SMT_ETH', 'FUN_ETH', 'PAY_ETH',
                        'ARPA_ETH', 'BIFI_BTC', 'RED_ETH', 'OST_ETH', 'LUN_ETH', 'FUN_USDT', 'MET_ETH', 'LBA_ETH', 'BFT_USDT', 'MDS_ETH', 'STX_USDT', 'PAY_BTC', 'BFT_ETH', 'STX_ETH', 'NBOT_ETH', 'SOUL_USDT',
                        'DOCK_ETH', 'ELEC_ETH', 'BNTY_ETH', 'CELR_ETH', 'SOUL_ETH', 'DADI_ETH', 'REQ_ETH', 'ZPT_ETH', 'TSL_QTUM'],

               'hitbtc': ['XTZUSD', 'MITHUSD', 'ZRCBTC', 'ZENETH', 'EDGBTC', 'IHTBTC', 'AEONBTC', 'DGBETH', 'EOSUSD', 'ZECEOS', 'NEOTUSD', 'XZCUSD', 'SOCBTC', 'PPCUSD', 'BCHUSD', 'HBARBTC', 'EOSGUSD', 'ZRXBTC',
                          'OPTBTC', 'NGCUSD', 'APPCBTC', 'PHXETH', 'DRGNBTC', 'POA20USD', 'BOXEURS', 'PTOYBTC', 'XDNBTC', 'OKBBTC', 'CHSBBTC', 'BNBUSD', 'NCTBTC', 'BTCGUSD', 'COCOSUSD', 'CVCOINETH', 'SILKETH',
                          'GETBTC', 'FUNBTC', 'EXPBTC', 'ETCUSD', 'EMRXBTC', 'REPETH', 'NEOUSD', 'REVBTC', 'LSKETH', 'TRACETH', 'GHOSTBTC', 'CNDETH', 'BMHBTC', 'SNCBTC', 'DTRBTC', 'ERDBTC', 'HTMLETH', 'BQXUSD',
                          'SCLBTC', 'KNCETH', 'SMTUSD', 'HMQBTC', 'ACTBTC', 'BOXETH', 'ZECBCH', 'ETCBTC', 'IQUSD', 'QTUMBTC', 'ETHGUSD', 'LEOUSD', 'EDGUSD', 'MTXBTC', 'SBTCBTC', 'BNTETH', 'CURETH', 'KINDBTC',
                          'CROETH', 'SMTBTC', 'BTBBTC', 'ACATETH', 'AMMETH', 'SWFTCBTC', 'STXUSD', '1STBTC', 'GBXUSD', 'UTTBTC', 'AXPRBTC', 'NMRBTC', 'XMREOS', 'ACTUSD', 'NTKETH', 'EVXBTC', 'EURSUSD', 'BTTETH',
                          'IOTABTC', 'NUTEOS', 'EURSDAI', 'STMXBTC', 'SALTBTC', 'MBLUSD', 'DGBBTC', 'WAVESBCH', 'NTKBTC', 'AMMBTC', 'GNTETH', 'NIMETH', 'SMTETH', 'ALGOBTC', 'BTGUSD', 'USEETH', 'ACATUSD',
                          'TNTUSD', 'LINKUSD', 'CENNZETH', 'VETUSDT', 'ORMEUSBTC', 'KINDETH', 'DCRETH', 'DGBUSD', 'RCNUSD', 'BDGBTC', 'BQXBTC', 'EKOBTC', 'CLOETH', 'FYPBTC', 'IPXBTC', 'HOTBTC', 'AMMUSD', 'MGBTC',
                          'FLPETH', 'BTSBTC', 'ADXBTC', 'XRPDAI', 'XLMETH', 'CRPTBTC', 'WAXPBTC', 'FDZUSD', 'NXTETH', 'POABTC', 'NEOEOS', 'PXGUSD', 'PLBTBTC', 'SHIPBTC', 'HTMLBTC', 'GASUSD', 'QTUMETH', 'CDTUSD',
                          'CVCUSD', 'DICEETH', 'BOXBTC', 'TRXETH', 'ETHEURS', 'GNOBTC', 'GRINETH', 'CUTEETH', 'PAXGUSD', 'UBTBTC', 'BTTBTC', 'IOTAETH', 'BETRUSD', 'ZENBTC', 'XVGETH', 'REMUSD', 'CHATETH', 'ACTETH',
                          'ARPAUSD', 'WAVESUSD', 'VEOBTC', 'POA20BTC', 'MTXETH', 'TIMEETH', 'BCPTBTC', 'EMCUSDT', 'XAURETH', 'SRNBTC', 'NCTETH', 'XUCUSD', 'XPRBTC', 'SNCETH', 'DTRETH', 'LENDETH', 'ZAPETH',
                          'POA20DAI', 'ETHBNTBTC', 'MANABTC', 'QKCBTC', 'MLNBTC', 'FLPBTC', 'SOLOBTC', 'SNTUSD', 'USDTUSD', 'QKCETH', 'FXTETH', 'TRUEBTC', 'VSYSBTC', 'DCNETH', 'USGETH', 'GNOETH', 'GNTBTC',
                          'MESHUSD', 'BOSBTC', 'PHBBTC', 'REXUSD', 'EURSTUSD', 'XRPEURS', 'ZECBTC', 'ESHBTC', 'SWMBTC', 'DASHEURS', 'ADXETH', 'MLNETH', 'BCPTETH', 'NANOBTC', 'VIBEBTC', 'LAETH', 'LSKEOS',
                          'HVNBTC', 'NPLCETH', 'LTCUSD', 'SOLVEBTC', 'HBTETH', 'ELECBTC', 'PLAETH', 'PTOYETH', 'PADUSD', 'ETCETH', 'COVETH', 'NUTUSD', 'LRCBTC', 'STRATETH', 'VETETH', 'AGIBTC', 'XPRETH',
                          'LNCBTC', 'WAVESBTC', 'WTCBTC', 'ABTCBTC', 'SWFTCETH', 'NANOETH', 'ONTBTC', 'STRATBTC', 'GNXBTC', 'TUSDEOSDT', 'NEUBTC', 'BCNBTC', 'PAYETH', 'XPNTBTC', 'TNTETH', 'XRPETH', 'INKETH',
                          'ECABTC', 'ARDRBTC', 'XPNTETH', 'KINBTC', 'LSKBTC', 'VIBETH', 'FACEETH', 'USEBTC', 'AMBETH', 'SALTETH', 'NEXOUSD', 'IOTXBTC', 'ATOMBCH', 'LCXETH', 'CROBTC', 'XMRUSD', 'IDHBTC',
                          'LINKBTC', 'BCHTUSD', 'AXPRETH', 'PASSETH', 'CDTETH', 'OAXBTC', 'CPTBTC', 'PLUETH', 'NGCBTC', 'GBXETH', 'DATAUSD', 'XNSBTC', 'KEYBTC', 'TKYBTC', 'HBARUSD', 'XUCETH', 'HSRBTC', 'TNTBTC',
                          'SMARTBTC', 'TRSTBTC', 'LNDETH', 'UTTETH', 'AUCETH', 'DCRBTC', 'DRTUSDT', 'WINGSBTC', 'GTBTC', 'BMCUSD', 'EKOUSDT', 'ADXUSD', 'MKRBTC', 'LTCDAI', 'TNCUSD', 'BDPETH', 'ONEBTC', 'DOGEBTC',
                          'ARNBTC', 'RCNETH', 'NAVUSD', 'SRNUSD', 'ACATBTC', 'ZRXETH', 'BMCBTC', 'GVTETH', 'RAISEBTC', 'VIBUSD', 'XDNUSD', 'BCNETH', 'MITXETH', 'PITCHETH', 'EXMBTC', 'OMGUSD', 'IPLETH', 'TIMEBTC',
                          'MCOETH', 'REXBTC', 'FDZBTC', 'HTBTC', 'MTHBTC', 'HEDGUSD', 'ICXUSD', 'SCCBTC', 'BETBTC', 'MKRETH', 'XNSUSD', 'DENTBTC', 'IDRTBTC', 'IPLBTC', 'SWTETH', 'NEXOETH', 'ZAPBTC', 'CMCTBTC',
                          'COMPUSD', 'CBCETH', 'SENTETH', 'ZILUSD', 'TDPBTC', 'XAURBTC', 'MTLBTC', 'LINKETH', 'POLYETH', 'BTMUSD', 'REPUSDT', 'NEBLBTC', 'SBTCUSDT', 'DATAETH', 'BATBTC', 'STEEMBTC', 'LTCEOS',
                          'CURBTC', 'BYTZBTC', 'PMAETH', 'AYAUSD', 'APPCETH', 'PROBTC', 'ETHDAI', 'EVXETH', 'LOOMBTC', 'BTCUSD', 'BATUSD', 'HMQETH', 'CURUSD', 'DRGBTC', 'DICEBTC', 'ADKBTC', 'COMPBTC', 'BDGETH',
                          'DRTBTC', 'XTZBTC', 'BATETH', 'ETCBCH', 'TRXEOS', 'WBTCETH', 'C20ETH', 'BTCEURS', 'DENTUSD', 'CHZBTC', 'BDPUSD', 'CHSBETH', 'DAYUSD', 'NEOBTC', 'NPLCBTC', 'STARETH', 'USDTGUSD',
                          'XCONBTC', 'LEVLBTC', 'BTCPAX', 'PLRETH', 'PARTBTC', 'ELECETH', 'ADAETH', 'PREBTC', 'MANUSD', 'BCHEURS', 'NEODAI', 'ERKBTC', 'NANOUSD', 'HEDGBTC', 'MGETH', 'CVCOINUSD', 'BITETH',
                          'IPLUSD', 'XRPEOS', 'FETBTC', 'XVGUSD', 'PAXGBTC', 'DCRUSD', 'USDDAI', 'XRPUSDT', 'PBTETH', 'DAGBTC', 'AVABTC', 'CUTEBTC', 'NEXOBTC', 'DAYBTC', 'MGEOS', 'SUBETH', 'PITCHBTC',
                          'MITXBTC', 'DAYETH', 'FLPUSD', 'MCOUSD', 'NXTBTC', 'POWRBTC', 'APPCUSD', 'PLRBTC', 'CVCOINBTC', 'XTZETH', 'NCTUSD', 'BTCTUSD', 'CHPETH', 'SENSOUSD', 'MYSTBTC', 'DLTBTC', 'HTMLUSD',
                          'DITETH', 'REMBTC', 'EOSETH', 'DAGETH', 'RLCBTC', 'DNABTC', 'FOTABTC', 'STORJETH', 'MKRUSD', 'NEOEURS', 'SBDBTC', 'SPCETH', 'ETHPAX', 'SBDETH', 'ELFBTC', 'FTXETH', 'DENTETH',
                          'ELECUSD', 'STORJUSD', 'DGTXETH', 'TELBTC', 'C20BTC', 'PMAUSD', 'PNTBTC', 'CNDBTC', 'ENJUSD', 'BETRBTC', 'ZENUSD', 'UTKBTC', 'SWMETH', 'CVCBTC', 'JNTETH', 'ETPBTC', 'ETHBTC', 'ZPRETH',
                          'FOTAETH', 'ZILBTC', 'APLUSD', 'ARPABTC', 'USDEOSDT', 'ICXETH', 'INKBTC', 'POA20ETH', 'XEMUSD', 'DGBTUSD', 'NPXSBTC', 'XLMBCH', 'HVNETH', 'LTCEURS', 'MESHBTC', 'NIMBTC', 'DATXBTC',
                          'HTUSD', 'FXTBTC', 'WINUSD', 'IHTUSD', 'NTKUSD', 'ADABCH', 'PBTBTC', 'ZECUSD', 'GSTBTC', 'BSVBTC', 'GASBTC', 'CBCBTC', 'MCOBTC', 'ATOMETH', 'MTLETH', 'SENTBTC', 'GBXBTC', 'XRCBTC',
                          'CPAYETH', 'GSTUSD', 'POEBTC', 'SURBTC', 'SOLOUSD', 'LOCBTC', 'BNTUSD', 'WIKIBTC', 'PPTBTC', 'ZRXTUSD', 'VSYSUSD', 'WAXPUSD', 'TVETH', 'DCNUSD', 'BMCETH', 'CVTBTC', 'APMBTC', 'BCHDAI',
                          'ZSCETH', 'BCNEOS', 'ZRXUSD', 'LENDBTC', 'CBCUSD', 'NUTBTC', 'DOVBTC', 'KMDBTC', 'XDNETH', 'TUSDUSDC', 'ETPUSD', 'AYABTC', 'EURSEOSDT', 'ECAUSD', 'MITHETH', 'XZCETH', 'ARNETH',
                          'IOTAUSD', 'LUNBTC', 'XEMBTC', 'RVNBTC', 'EOSDAI', 'BETETH', 'DASHEOS', 'EVXUSD', 'FUNUSD', 'ONTBCH', 'ZECEURS', 'BCDBTC', 'SPCUSD', 'XMRBTC', 'USGUSD', 'CVTUSD', 'LTCTUSD', 'DRGETH',
                          'BCHETH', 'ABYSSETH', 'MTXUSD', 'CUTEEOS', 'CHZUSD', 'DGTXUSD', 'ETHEOSDT', 'ENJETH', 'EOSPAX', 'NWCBTC', 'USGBTC', 'USDUSDC', 'CLOBTC', 'BANCAETH', 'NLC2BTC', 'IOSTUSD', 'BTCBBTC',
                          'BERRYBTC', 'ARTBTC', 'GRINBTC', 'VITAEBTC', 'XBPBTC', 'OMGBTC', 'BTXUSD', 'BTGETH', 'BTMETH', 'MDABTC', 'KRLBTC', 'IGNISETH', 'BCHBTC', 'UUUETH', 'SURETH', 'POLYBTC', 'NEBLETH',
                          'PLABTC', 'SUBUSD', 'AVTETH', 'BERRYUSD', 'BANCABTC', 'NXTUSD', 'ENJBTC', 'LRCETH', 'TRIGXBTC', 'UUUBTC', 'PASSBTC', 'POAUSD', 'CRPTUSD', 'DATXETH', 'ANTBTC', 'LAMBBTC', 'CMCTUSD',
                          'SRNETH', 'UTTUSD', 'ALGOUSD', 'STXETH', 'DAPPEOS', 'RFRBTC', 'CVTETH', 'AMBBTC', 'ROOBEEBTC', 'SNTETH', 'BSTBTC', 'LCCBTC', 'DASHBCH', 'BCNUSD', 'RCNBTC', 'MINBTC', 'ATOMUSD',
                          'RFRUSD', 'KMDUSD', 'BTCBUSD', 'KINETH', 'POSTUSD', 'OAXETH', 'DITBTC', 'ETNUSD', 'PPCBTC', 'XMRETH', 'AEBTC', 'FDZETH', 'COMPETH', 'IQBTC', 'BNKBTC', 'CENNZBTC', 'PPTETH', 'SUBBTC',
                          'USDIDRT', 'BCPTUSDT', 'OCNBTC', 'DGDBTC', 'HGTETH', 'VRABTC', 'STXBTC', 'AERGOBTC', 'HGTBTC', 'TRADBTC', 'TRXBCH', 'PLBTETH', 'IGNISBTC', 'NGCETH', 'FTTUSD', 'POADAI', 'REPBTC',
                          'DAPPBTC', 'DNTBTC', 'CDTBTC', 'YCCBTC', 'BCDUSD', 'NWCUSD', 'SNGLSBTC', 'ICXBTC', 'JSTUSD', 'BERRYETH', 'OAXUSD', 'PKTBTC', 'TRXUSD', 'DRTETH', 'COVBTC', 'SURUSD', 'PREETH', 'ZECETH',
                          'PAYBTC', 'MYSTETH', 'ABYSSBTC', 'DAIUSDC', 'FUNETH', 'BLZBTC', 'DAVBTC', 'GNTUSD', 'BSVBCH', 'TKNBTC', 'PKTETH', 'VRAETH', 'IDHETH', 'SWFTCUSD', 'ERTBTC', 'NEUUSD', 'XMCETH', 'SPCBTC',
                          'CELETH', 'SEELEBTC', 'MESHETH', 'XPNTUSD', 'XZCBTC', 'MAIDBTC', 'NEUETH', 'PLRUSD', 'AUTOBTC', 'RENBTC', 'MAIDUSD', 'DATABTC', 'LOCUSD', 'AUCBTC', 'TVBTC', 'DASHETH', 'KEYETH',
                          'DAVETH', 'LAVABTC', 'KAVABTC', 'AVAETH', 'LINKBCH', 'GNXETH', 'ETPETH', 'LSKUSD', 'POEETH', 'EKOETH', 'NEOETH', 'LOOMETH', 'BTCDAI', 'UTKETH', 'XMRTUSD', 'ADAUSD', 'UTKUSD', 'EMCETH',
                          'TVUSD', 'EOSEURS', 'OCNETH', 'DAPSBTC', 'SHIPETH', 'KMDETH', 'BRDGUSD', 'INDETH', 'ADABTC', 'MKRDAI', 'COCOSBTC', 'MITHBTC', 'BSVUSD', 'SWMUSD', 'SBTCETH', 'ELFUSD', 'NRGBTC',
                          'CHATUSD', 'PHXBTC', 'EOSEOSDT', 'DASHBTC', 'MTHETH', 'ZSCUSD', 'REVUSD', 'CHATBTC', 'LTCETH', 'CLOUSD', 'SENTUSD', 'VETBTC', 'MANAETH', 'BTCEOSDT', 'LTCBCH', 'GHOSTUSD', 'ZSCBTC',
                          'TUSDDAI', 'OMGBCH', 'ETHTUSD', 'CUTEUSD', 'KNCBTC', 'PNTETH', 'DGTXBTC', 'CELBTC', 'ETHUSD', 'WIKIUSD', 'GSTETH', 'XLMUSD', 'ETNETH', 'MGUSD', 'XMREURS', 'RAISEETH', 'BYTZUSD', 'EOSBCH',
                          'BTCSHORTUSD', 'IOSTBTC', 'BNBBTC', 'PBTTBTC', 'SBDUSD', 'XMCBTC', 'ALGOETH', 'EMCBTC', 'VIBBTC', 'PLAUSD', 'STRATUSD', 'XPRUSD', 'BNTBTC', 'STORJBTC', 'ERKUSD', 'BRDGETH', 'AMBUSD',
                          'ORMEUSETH', 'ECAETH', 'ONTUSD', 'ATOMBTC', 'SNCUSD', 'LCXBTC', 'BETRETH', 'QTUMUSD', 'SCBTC', 'REXETH', 'FTTBTC', 'BTMBTC', 'XMRDAI', 'DAIEOSDT', 'INKUSD', 'WAXPETH', 'XLMBTC', 'SANETH',
                          'IPXUSD', 'TRXBTC', 'TELETH', 'CELRBTC', 'BRDBTC', 'DASHUSD', 'WIKIETH', 'DBIXBTC', 'ETNBTC', 'SNTBTC', 'LOCETH', 'XRPBCH', 'ZAPUSD', 'MAIDETH', 'ONTETH', 'BNKUSD', 'DOVETH', 'XMRBCH',
                          'BOXEOS', 'MOFBTC', 'HEXBTC', 'XUCBTC', 'PLUBTC', 'FACEBTC', 'GRINUSD', 'EDGETH', 'USDPAX', 'SEELEUSD', 'TNCBTC', 'REMETH', 'SIGBTC', 'PXGBTC', 'SMARTUSD', 'BDPBTC', 'BTXBTC', 'TAUBTC',
                          'XEMETH', 'ARDRUSD', 'CROUSD', 'KNCUSD', 'BRDETH', 'AVAUSD', 'DCTBTC', 'SMARTETH', 'GASETH', 'POAETH', 'YOYOWBTC', 'XEMEOS', 'POWRETH', 'BNBETH', 'BTTUSD', 'SWTBTC', 'MANBTC', 'BQXETH',
                          'GLEECBTC', 'EOSBTC', 'ETHUSDC', '1STETH', 'OMGETH', 'ROXETH', 'PHXUSD', 'IHTETH', 'BNKETH', 'BUSDUSD', 'XVGBTC', 'NAVBTC', 'CUREBTC', 'CNDUSD', 'ERKETH', 'DOGEETH', 'CMCTETH', 'PROETH',
                          'XRPBTC', 'BANCAUSD', 'KICKBTC', 'MANETH', 'BRDGBTC', 'LTCBTC', 'DOGEUSD', 'MANAUSD', 'XMCUSDT', 'BTCUSDC', 'MATICBTC', 'FTXBTC', 'BTGBTC', 'PMABTC'],

               'huobi': ['btcusd', 'ethusd', 'btcusdt', 'bsvusd', 'ethusdt', 'bchusd', 'bsvusdt', 'eosusdt', 'bchusdt', 'ltcusdt', 'xrpusdt', 'adausdt', 'ethbtc', 'aacbtc', 'zecusdt', 'etcusdt', 'htusdt',
                         'linkusdt', 'dacbtc', 'usdthusd', 'kcashbtc', 'ttusdt', 'kcasheth', 'bsvbtc', 'trxusdt', 'kcashht', 'zilusdt', 'crobtc', 'eosbtc', 'bchbtc', 'yeebtc', 'cvntbtc', 'ontusdt', 'crousdt',
                         'emusdt', 'actusdt', 'croht', 'iostusdt', 'atomusdt', 'dashusdt', 'xtzusdt', 'xrpbtc', 'xlmusdt', 'rsrusdt', 'btchusd', 'ltcbtc', 'letusdt', 'qtumusdt', 'htbtc', 'omgusdt', 'cvnteth',
                         'neousdt', 'batusdt', 'neobtc', 'etcbtc', 'thetausdt', 'xmrbtc', 'xmrusdt', 'eoseth', 'letbtc', 'vetusdt', 'zilbtc', 'nexobtc', 'hiveusdt', 'nexoeth', 'algousdt', 'lambusdt', 'nodeusdt',
                         'xmxbtc', 'zecbtc', 'bchht', 'vsysusdt', 'ognusdt', 'nulsusdt', 'batbtc', 'ctxcusdt', 'storjusdt', 'elausdt', 'linkbtc', 'ctxceth', 'renusdt', 'bhdusdt', 'covabtc', 'steemusdt', 'rsrbtc',
                         'hteth', 'socusdt', 'hcusdt', 'adabtc', 'vetbtc', 'btmusdt', 'nasusdt', 'irisbtc', 'zrxusdt', 'trxbtc', 'bttusdt', 'xtzbtc', 'ethhusd', 'kncbtc', 'mdsusdt', 'actbtc', 'mcobtc', 'mxusdt',
                         'elfusdt', 'xlmbtc', 'eoshusd', 'topusdt', 'dtausdt', 'bixusdt', 'btsusdt', 'embtc', 'aeusdt', 'hptusdt', 'cmtusdt', 'wiccusdt', 'forusdt', 'irisusdt', 'atpusdt', 'hivebtc', 'hotbtc',
                         'chateth', 'linketh', 'smtusdt', 'ektusdt', 'vidyusdt', 'iostbtc', 'mxcbtc', 'propybtc', 'nknusdt', 'covaeth', 'creusdt', 'tnbbtc', 'fsnusdt', 'vsysbtc', 'atombtc', 'ontbtc', 'renbtc',
                         'paiusdt', 'dashbtc', 'iotausdt', 'usdchusd', 'hptht', 'bcvbtc', 'reqbtc', 'bcdbtc', 'lolusdt', 'bsvhusd', 'iicbtc', 'uuuusdt', 'ltcht', 'xmxeth', 'sncbtc', 'lbausdt', 'trxeth', 'ctxcbtc',
                         'waxpbtc', 'ftibtc', 'kanusdt', 'ckbusdt', 'cvcusdt', 'elabtc', 'boxbtc', 'xzcusdt', 'xvgbtc', 'itcusdt', 'newusdt', 'xrpht', 'dogeusdt', 'uipusdt', 'bchhusd', 'socbtc', 'gxcusdt',
                         'ruffusdt', 'thetabtc', 'ogousdt', 'qtumeth', 'omgbtc', 'btgbtc', 'zrxbtc', 'hptbtc', 'ftieth', 'gnxbtc', 'stkbtc', 'gtusdt', 'manausdt', 'bhtusdt', 'nulsbtc', 'hthusd', 'eosht', 'xemusdt',
                         'arpausdt', 'egccbtc', 'rtebtc', 'sntusdt', 'daceth', 'adaeth', 'scbtc', 'reneth', 'paxhusd', 'ognbtc', 'hoteth', 'zileth', 'akrousdt', 'aaceth', 'steembtc', 'oneusdt', 'aidocbtc',
                         'ltchusd', 'algobtc', 'gntusdt', 'wavesusdt', 'dashht', 'wtcusdt', 'engeth', 'hcbtc', 'wanbtc', 'snceth', 'dcrusdt', 'blzbtc', 'gasbtc', 'icxbtc', 'nasbtc', 'iiceth', 'dtabtc', 'yccbtc',
                         'egtusdt', 'kanbtc', 'nknbtc', 'btmbtc', 'iosteth', 'qtumbtc', 'utkbtc', 'ycceth', 'lxtusdt', 'dbcbtc', 'zenbtc', 'storjbtc', 'nanobtc', 'kaneth', 'mteth', 'cvcoineth', 'xrphusd',
                         'knceth', 'rteeth', 'ckbbtc', 'lambbtc', 'hitusdt', 'fairbtc', 'onteth', 'uceth', 'ucbtc', 'iostht', 'etchusd', 'cvcoinbtc', 'itcbtc', 'manabtc', 'wxtusdt', 'zechusd', 'nanousdt',
                         'lymbtc', 'mtbtc', 'skmusdt', 'atometh', 'ttht', 'lambeth', 'yeeeth', 'lbabtc', 'btttrx', 'etcht', 'soceth', 'aebtc', 'xzcbtc', 'dgbbtc', 'cmtbtc', 'pvtusdt', 'iotabtc', 'paibtc',
                         'datxbtc', 'xtzeth', 'uuubtc', 'qunbtc', 'btsbtc', 'triobtc', 'dogebtc', 'bixbtc', 'swftcbtc', 'sceth', 'butbtc', 'nodebtc', 'veteth', 'forbtc', 'quneth', 'thetaeth', 'bcveth', 'crebtc',
                         'ttbtc', 'fsnbtc', 'rsrht', 'elfbtc', 'fttusdt', 'cnnsusdt', 'ogobtc', 'ocnusdt', 'sspeth', 'kmdbtc', 'wavesbtc', 'xmreth', 'propyeth', 'npxsbtc', 'xvgeth', 'dtaeth', 'stketh', 'btteth',
                         'btmeth', 'adahusd', 'gxcbtc', 'bateth', 'tnbeth', 'xlmeth', 'leteth', 'shebtc', 'tusdhusd', 'reqeth', 'gnxeth', 'bttbtc', 'mxbtc', 'sntbtc', 'nknht', 'aidoceth', 'dcrbtc', 'manbtc',
                         'elfeth', 'cnnbtc', 'loombtc', 'cmteth', 'wiccbtc', 'egcceth', 'waneth', 'bhtbtc', 'cvcbtc', 'chatbtc', 'nulseth', 'lbaeth', 'gntbtc', 'omgeth', 'etnbtc', 'atpbtc', 'idtbtc', 'buteth',
                         'waxpeth', 'zeneth', 'bhdbtc', 'pcbtc', 'lskbtc', 'xlmhusd', 'wtcbtc', 'dashhusd', 'paybtc', 'ekteth', 'boxeth', 'dockusdt', 'lymeth', 'abtbtc', 'mdsbtc', 'zrxeth', 'polybtc', 'xzceth',
                         'tosbtc', 'topbtc', 'dgbeth', 'lxtbtc', 'utketh', 'onebtc', 'ekobtc', 'powrbtc', 'uuueth', 'sspbtc', 'algoeth', 'paieth', 'naseth', 'uipbtc', 'wxtbtc', 'steemeth', 'hceth', 'pnteth',
                         'mxht', 'lolbtc', 'newbtc', 'gtcbtc', 'lunbtc', 'arpabtc', 'topceth', 'mcoeth', 'appcbtc', 'swftceth', 'lxteth', 'toseth', 'ruffbtc', 'cvceth', 'geteth', 'utketh', 'swftceth', 'appcbtc',
                         'aeeth', 'naseth', 'gvebtc', 'lolbtc', 'topcbtc', 'geteth', 'ruffeth', 'ncasheth', 'smtbtc', 'cnneth', 'loometh', 'astbtc', 'pntbtc', 'ardrbtc', 'sheeth', 'vidybtc', 'gtceth', 'dgdeth',
                         'idteth', 'npxseth', 'gscbtc', 'ardreth', 'mtxbtc', 'mtnbtc', 'dcreth', 'srneth', 'srnbtc', 'hitbtc', 'ocnbtc', 'faireth', 'mdseth', 'iriseth', 'wicceth', 'mexeth', 'trioeth', 'evxeth',
                         'gsceth', 'algoeth', 'smteth', 'acteth', 'etneth', 'ncceth', 'icxeth', 'zlaeth', 'lsketh', 'waveseth', 'kmdeth', 'getbtc', 'gxceth', 'meeteth', 'blzeth', 'maneth', 'edubtc', 'ugasbtc',
                         'fttbtc', 'wprbtc', 'qspbtc', 'qashbtc', 'lambht', 'manaeth', 'grseth', 'evxbtc', 'nodeht', 'tntbtc', 'grsbtc', 'wtceth', 'nanoeth', 'itceth', 'bftbtc', 'gnteth', 'ckbht', 'vsysht',
                         'bfteth', 'datxeth', 'rcnbtc', 'luneth', 'gtbtc', 'gaseth', 'egtbtc', 'mtht', 'iotaeth', 'datbtc', 'btseth', 'xembtc', 'dgdbtc', 'dateth', 'saltbtc', 'edueth', 'dockbtc', 'skmbtc',
                         'powreth', 'ncashbtc', 'phxbtc', 'hiteth', 'rdnbtc', 'akroht', 'topht', 'ncashbtc', 'newht', 'fsnht', 'bhdht', 'hiveht', 'pvtbtc', 'atpht', 'akroht', 'skmbtc', 'bhtht', 'arpaht',
                         'meetbtc', 'ognht', 'gveeth', 'ocneth', 'mexbtc', 'appceth', 'rdnbtc', 'mtneth', 'emht', 'mtxeth', 'ogoht', 'fttht', 'nccbtc', 'lolht', 'adxbtc', 'gtht', 'skmht', 'mtlbtc', 'ugaseth',
                         'oneht', 'cnnsht', 'payeth', 'qasheth', 'creht', 'forht', 'polyeth', 'zlabtc', 'wxtht', 'vidyht', 'egtht', 'engbtc', 'wpreth', 'sbtcbtc', 'dbceth', 'pvtht', 'ostbtc', 'pceth', 'cnnsbtc',
                         'docketh', 'bifibtc'],

               'kraken': ['BTC/EUR', 'BTC/USD', 'ETH/USD', 'ETH/EUR', 'USDT/USD', 'USDT/EUR', 'LINK/USD', 'ETH/BTC', 'XTZ/USD', 'LINK/EUR', 'XRP/USD', 'BCH/USD', 'ADA/USD', 'XTZ/EUR', 'BTC/GBP', 'BTC/USDT',
                          'ADA/EUR', 'ZEC/BTC', 'BCH/EUR', 'XRP/EUR', 'MLN/EUR', 'ZEC/EUR', 'ZEC/USD', 'XTZ/BTC', 'LTC/USD', 'LINK/BTC', 'BTC/CAD', 'USDC/EUR', 'PAXG/USD', 'USDT/JPY', 'USDC/USD', 'XLM/EUR',
                          'XMR/BTC', 'XMR/EUR', 'ETH/USDT', 'ATOM/EUR', 'XLM/USD', 'LINK/ETH', 'BAT/EUR', 'ALGO/USD', 'BAT/USD', 'LTC/EUR', 'ALGO/BTC', 'DAI/USD', 'ATOM/BTC', 'XMR/USD', 'DASH/EUR', 'MLN/ETH',
                          'REP/EUR', 'ADA/BTC', 'DAI/EUR', 'SC/EUR', 'PAXG/EUR', 'DASH/USD', 'MLN/USD', 'ATOM/USD', 'BTC/CHF', 'PAXG/BTC', 'USDC/USDT', 'REP/BTC', 'SC/BTC', 'XTZ/ETH', 'BTC/USDC', 'NANO/EUR',
                          'EOS/EUR', 'XRP/BTC', 'EOS/USD', 'NANO/USD', 'BCH/BTC', 'BAT/BTC', 'ETH/GBP', 'ALGO/EUR', 'GNO/EUR', 'SC/USD', 'REP/USD', 'DAI/USDT', 'MLN/BTC', 'USDT/GBP', 'LTC/BTC', 'BTC/JPY',
                          'ETH/CAD', 'ETC/EUR', 'OMG/EUR', 'GNO/BTC', 'NANO/BTC', 'ADA/ETH', 'DASH/BTC', 'XLM/BTC', 'TRX/EUR', 'DOGE/EUR', 'ETH/JPY', 'GNO/ETH', 'TRX/USD', 'QTUM/USD', 'NANO/ETH', 'XRP/ETH',
                          'QTUM/EUR', 'ETH/USDC', 'ICX/EUR', 'SC/ETH', 'ICX/USD', 'WAVES/USD', 'ETH/DAI', 'OMG/USD', 'ETC/ETH', 'WAVES/EUR', 'ETC/USD', 'BCH/USDT', 'ETH/CHF', 'XRP/CAD', 'BAT/ETH', 'EOS/ETH',
                          'USDT/CAD', 'OXT/BTC', 'LSK/BTC', 'OMG/BTC', 'XRP/USDT', 'OXT/USD', 'BCH/ETH', 'XRP/JPY', 'ATOM/ETH', 'OXT/EUR', 'PAXG/ETH', 'USDT/CHF', 'WAVES/BTC', 'ETC/BTC', 'ALGO/ETH', 'GNO/USD',
                          'EOS/BTC', 'QTUM/BTC', 'TRX/BTC', 'DOGE/BTC', 'DOGE/USD', 'ICX/BTC', 'LSK/EUR', 'LTC/ETH', 'XRP/GBP', 'BTC/DAI', 'REP/ETH', 'OMG/ETH', 'ICX/ETH', 'OXT/ETH', 'LTC/USDT', 'QTUM/ETH',
                          'TRX/ETH', 'LSK/USD', 'LSK/ETH', 'LTC/GBP', 'BCH/GBP', 'WAVES/ETH'],

               'kucoin': ['BTC-USDT', 'ETH-USDT', 'KCS-USDT', 'BCHSV-USDT', 'EOS-USDT', 'ETH-BTC', 'ATOM-USDT', 'VIDT-BTC', 'ADA-USDT', 'BCHABC-USDT', 'BCHSV-BTC', 'NIM-BTC', 'ADA-BTC', 'XRP-USDT', 'SENSO-USDT',
                          'ATOM-BTC', 'SNX-USDT', 'LTC-USDT', 'TRX-USDT', 'NIM-ETH', 'TRX-BTC', 'VET-BTC', 'VET-USDT', 'OPEN-ETH', 'XRP-BTC', 'ZEC-USDT', 'XTZ-USDT', 'BCHSV-ETH', 'DX-ETH', 'XTZ-BTC', 'AMPL-USDT',
                          'SENSO-BTC', 'USDN-USDT', 'ZEC-BTC', 'PAZZI-USDT', 'KCS-BTC', 'CAG-BTC', 'VID-BTC', 'XLM-USDT', 'VET-ETH', 'EOS-BTC', 'TOMO-BTC', 'WOM-USDT', 'SUTER-USDT', 'FTM-BTC', 'BCHABC-BTC',
                          'DRGN-BTC', 'KNC-BTC', 'VRA-BTC', 'AVA-USDT', 'ETC-USDT', 'SNX-BTC', 'OCEAN-BTC', 'AVA-BTC', 'ZRX-BTC', 'DASH-USDT', 'TOKO-USDT', 'VID-USDT', 'ZIL-BTC', 'SNX-ETH', 'AKRO-BTC', 'BEPRO-BTC',
                          'ATOM-ETH', 'KSM-BTC', 'DASH-BTC', 'KCS-ETH', 'DGTX-ETH', 'XSR-USDT', 'DASH-ETH', 'KSM-USDT', 'USDT-USDC', 'BEPRO-USDT', 'LUNA-USDT', 'EOS-ETH', 'LUNA-BTC', 'AMPL-BTC', 'TRX-ETH',
                          'CHSB-BTC', 'LTC-BTC', 'SXP-BTC', 'VI-USDT', 'TOMO-USDT', 'XRP-ETH', 'NEO-BTC', 'XMR-BTC', 'XDB-USDT', 'XLM-ETH', 'XNS-USDT', 'NEO-USDT', 'BCHABC-ETH', 'SXP-USDT', 'REV-USDT', 'UTK-BTC',
                          'LTC-ETH', 'ETC-BTC', 'XNS-BTC', 'DGB-USDT', 'DGB-BTC', 'BTC-USDC', 'DGB-ETH', 'XLM-BTC', 'ROOBEE-BTC', 'PRE-BTC', 'KNC-ETH', 'AKRO-USDT', 'NWC-USDT', 'IOST-BTC', 'BNB-BTC', 'VRA-USDT',
                          'KICK-ETH', 'COTI-BTC', 'ALGO-BTC', 'ETN-BTC', 'DAG-BTC', 'XDB-BTC', 'AOA-USDT', 'IOTX-BTC', 'BNB-USDT', 'ENJ-BTC', 'TEL-BTC', 'QKC-BTC', 'SUTER-BTC', 'NWC-BTC', 'ONT-BTC', 'AVA-ETH',
                          'NULS-BTC', 'ONT-USDT', 'FTM-ETH', 'UTK-ETH', 'DRGN-ETH', 'LYXe-USDT', 'SYLO-USDT', 'CAPP-BTC', 'DX-BTC', 'COMP-USDT', 'CHR-BTC', 'OCEAN-ETH', 'DBC-BTC', 'ENQ-BTC', 'DGTX-BTC', 'DATX-BTC',
                          'AERGO-BTC', 'BPT-BTC', 'CHR-USDT', 'REQ-BTC', 'RIF-BTC', 'CS-BTC', 'JAR-USDT', 'TRAC-BTC', 'CHSB-ETH', 'COTI-USDT', 'KAT-USDT', 'OPQ-ETH', 'NPXS-BTC', 'DERO-BTC', 'CRPT-BTC', 'DAPPT-BTC',
                          'QTUM-BTC', 'ETN-USDT', 'PIVX-BTC', 'RBTC-BTC', 'BTC-TUSD', 'MKR-BTC', 'MAN-BTC', 'DAPPT-USDT', 'ZIL-ETH', 'BAX-BTC', 'AVA-NEO', 'ALGO-USDT', 'CS-ETH', 'ONE-BTC', 'NEBL-BTC', 'ELA-BTC',
                          'ZRX-ETH', 'TRY-BTC', 'DOCK-BTC', 'ADB-BTC', 'ENQ-USDT', 'GMB-ETH', 'XMR-ETH', 'NRG-BTC', 'LYXe-ETH', 'ETH-USDC', 'VRAB-BNB', 'OLT-BTC', 'CBC-ETH', 'CRO-BTC', 'IOTX-ETH', 'GRIN-BTC',
                          'COFI-BTC', 'TEL-ETH', 'BCD-BTC', 'CPC-BTC', 'FET-BTC', 'NEO-ETH', 'ETC-ETH', 'IOST-ETH', 'MTV-BTC', 'DOCK-ETH', 'BOLT-BTC', 'TOMO-ETH', 'SOUL-BTC', 'TRY-USDT', 'ZEL-BTC', 'DAG-USDT',
                          'GRIN-USDT', 'BTC-DAI', 'GMB-BTC', 'SOLVE-BTC', 'VSYS-BTC', 'KICK-BTC', 'AMB-BTC', 'USDT-DAI', 'SUSD-USDT', 'JAR-BTC', 'NANO-USDT', 'CAG-ETH', 'LOKI-BTC', 'XYO-BTC', 'REQ-ETH',
                          'WAXP-BTC', 'FX-BTC', 'ARX-USDT', 'MHC-BTC', 'ONT-ETH', 'BTT-USDT', 'NANO-BTC', 'KAT-BTC', 'QKC-ETH', 'BTM-BTC', 'DAG-ETH', 'ARPA-USDT', 'CRO-USDT', 'EDN-BTC', 'FKX-BTC', 'AXPR-ETH',
                          'MTV-USDT', 'BTC-PAX', 'ETH-TUSD', 'SYLO-BTC', 'TEL-USDT', 'OMG-BTC', 'GRIN-ETH', 'BAX-ETH', 'EOSC-USDT', 'PMGT-USDT', 'XYO-ETH', 'TRAC-ETH', 'HPB-BTC', 'AGI-BTC', 'TKY-BTC', 'BTT-TRX',
                          'ENJ-ETH', 'AION-BTC', 'BTM-ETH', 'SUSD-ETH', 'CHZ-BTC', 'NOIA-BTC', 'CRPT-ETH', 'CPC-ETH', 'GO-BTC', 'WAN-BTC', 'REV-BTC', 'MKR-ETH', 'PIVX-ETH', 'ETN-ETH', 'FKX-ETH', 'LTC-KCS',
                          'ONE-USDT', 'NEO-KCS', 'HPB-ETH', 'BTT-BTC', 'BLOC-USDT', 'VRAB-ETH', 'EXY-BTC', 'LOOM-BTC', 'LOKI-ETH', 'FX-ETH', 'AERGO-ETH', 'KEY-BTC', 'ALGO-ETH', 'CS-KCS', 'SNT-ETH', 'XRP-KCS',
                          'SNT-BTC', 'WTC-BTC', 'ANKR-BTC', 'NRG-ETH', 'MTC-BTC', 'COV-BTC', 'ELA-ETH', 'TFD-BTC', 'OMG-ETH', 'CHP-ETH', 'WIN-BTC', 'ITC-BTC', 'OPEN-BTC', 'BTT-ETH', 'FET-ETH', 'PPT-BTC',
                          'SOUL-ETH', 'CSP-BTC', 'DACC-ETH', 'XEM-BTC', 'DENT-BTC', 'POWR-BTC', 'BOLT-USDT', 'GAS-BTC', 'DERO-USDT', 'DCR-BTC', 'NULS-ETH', 'NPXS-ETH', 'DRGN-NEO', 'GAS-NEO', 'WIN-USDT',
                          'POWR-ETH', 'AGI-ETH', 'WAXP-ETH', 'ELF-BTC', 'TIME-BTC', 'HC-BTC', 'AXPR-BTC', 'XEM-USDT', 'FOTA-BTC', 'MANA-BTC', 'ADB-ETH', 'CXO-BTC', 'MAN-ETH', 'CHP-BTC', 'NANO-ETH', 'GO-USDT',
                          'STX-BTC', 'DACC-BTC', 'PMGT-BTC', 'EOS-KCS', 'TFD-ETH', 'OPQ-BTC', 'STX-USDT', 'ACOIN-USDT', 'LOC-BTC', 'LYM-BTC', 'LOOM-ETH', 'ACT-BTC', 'MANA-ETH', 'TOKO-BTC', 'NIX-BTC', 'VSYS-USDT',
                          'LSK-BTC', 'DENT-ETH', 'TKY-ETH', 'ETH-DAI', 'PLAY-BTC', 'ITC-USDT', 'CXO-ETH', 'SNTR-ETH', 'WIN-TRX', 'COFI-ETH', 'EDN-ETH', 'NIX-ETH', 'MAP-USDT', 'OLT-ETH', 'LSK-ETH', 'TKY-USDT',
                          'SPND-BTC', 'CVC-BTC', 'MAP-BTC', 'DATX-ETH', 'MWAT-BTC', 'ACAT-BTC', 'TRTL-BTC', 'CV-BTC', 'ITC-ETH', 'TIME-ETH', 'MTV-ETH', 'EGT-BTC', 'USDT-PAX', 'ROAD-USDT', 'GO-ETH', 'MHC-ETH',
                          'NOIA-USDT', 'FOTA-ETH', 'MHC-USDT', 'DBC-ETH', 'ELF-ETH', 'WAN-ETH', 'MKR-DAI', 'ETH-PAX', 'AOA-BTC', 'KEY-ETH', 'AMIO-USDT', 'CSP-ETH', 'TFL-BTC', 'SUSD-BTC', 'BCD-ETH', 'WXT-USDT',
                          'MTV-KCS', 'CIX100-USDT', 'LYM-USDT', 'AION-ETH', 'MVP-BTC', 'FOTA-ETH', 'BU-ETH', 'GO-ETH', 'GO-KCS', 'WXT-BTC', 'WXT-BTC', 'CV-ETH', 'ACT-ETH', 'MVP-ETH', 'SPND-ETH', 'XRP-NEO',
                          'DCR-ETH', 'LYM-ETH', 'MWAT-ETH', 'BU-BTC', 'MTC-ETH', 'EGT-ETH', 'CAPP-ETH', 'COV-ETH', 'AMB-ETH', 'EOS-NEO', 'TRTL-ETH', 'META-BTC', 'XRP-TUSD', 'TFL-ETH', 'PLAY-ETH', 'HC-ETH',
                          'TKY-NEO', 'CVC-BTC', 'LOC-ETH', 'XRP-PAX'],


               'okex': ['spot/trade:BTC-USDT', 'spot/trade:BTC-USD', 'spot/trade:ETH-USD', 'spot/trade:ETH-USDT', 'spot/trade:OKB-ETH', 'spot/trade:KNC-USDT', 'spot/trade:ETC-BTC', 'spot/trade:DEP-USDK',
                        'spot/trade:OKB-BTC', 'spot/trade:TRUE-BTC', 'spot/trade:KNC-BTC', 'spot/trade:OKB-USDK', 'spot/trade:OKB-USDT', 'spot/trade:ETC-ETH', 'spot/trade:BCH-USDT', 'spot/trade:DEP-USDT',
                        'spot/trade:ETC-USDT', 'spot/trade:EOS-USDT', 'spot/trade:EOS-USD', 'spot/trade:USDT-USDK', 'spot/trade:BCH-USD', 'spot/trade:ZIL-USDT', 'spot/trade:LTC-USD', 'spot/trade:CRO-USDK',
                        'spot/trade:XTZ-USDT', 'spot/trade:NDN-USDK', 'spot/trade:BSV-USDT', 'spot/trade:LTC-USDT', 'spot/trade:GTO-ETH', 'spot/trade:LRC-USDT', 'spot/trade:BSV-BTC', 'spot/trade:TRX-USD',
                        'spot/trade:NDN-USDT', 'spot/trade:MCO-USDT', 'spot/trade:BSV-USD', 'spot/trade:ONT-USDT', 'spot/trade:IOST-USDT', 'spot/trade:SWFTC-ETH', 'spot/trade:IOTA-USDT', 'spot/trade:QTUM-USDT',
                        'spot/trade:CRO-USDT', 'spot/trade:XTZ-BTC', 'spot/trade:ITC-USDT', 'spot/trade:MANA-USDT', 'spot/trade:TRX-ETH', 'spot/trade:BCD-USDT', 'spot/trade:IOST-BTC', 'spot/trade:VITE-BTC',
                        'spot/trade:ETC-USD', 'spot/trade:OMG-BTC', 'spot/trade:GNX-ETH', 'spot/trade:SWFTC-BTC', 'spot/trade:TRX-BTC', 'spot/trade:PAX-USDT', 'spot/trade:ETC-OKB', 'spot/trade:XRP-USD',
                        'spot/trade:ELF-BTC', 'spot/trade:BTM-BTC', 'spot/trade:CVC-BTC', 'spot/trade:GTO-USDT', 'spot/trade:FAIR-USDT', 'spot/trade:NULS-USDT', 'spot/trade:KCASH-USDT', 'spot/trade:BTC-USDK',
                        'spot/trade:CRO-BTC', 'spot/trade:PAY-USDT', 'spot/trade:ETH-BTC', 'spot/trade:GNX-BTC', 'spot/trade:NEO-USDT', 'spot/trade:ICX-USDT', 'spot/trade:MCO-BTC', 'spot/trade:ZEC-BTC',
                        'spot/trade:LINK-USDT', 'spot/trade:DGB-USDT', 'spot/trade:NULS-ETH', 'spot/trade:XRP-USDT', 'spot/trade:ATOM-BTC', 'spot/trade:GAS-ETH', 'spot/trade:KCASH-BTC', 'spot/trade:ZEC-USDT',
                        'spot/trade:ETC-USDK', 'spot/trade:EOS-OKB', 'spot/trade:QTUM-BTC', 'spot/trade:ABT-USDT', 'spot/trade:NULS-BTC', 'spot/trade:STORJ-USDT', 'spot/trade:TRX-USDT', 'spot/trade:EC-USDT',
                        'spot/trade:EOS-BTC', 'spot/trade:ELF-ETH', 'spot/trade:BCH-BTC', 'spot/trade:HC-USDT', 'spot/trade:ELF-USDT', 'spot/trade:CVC-ETH', 'spot/trade:EOS-ETH', 'spot/trade:GAS-BTC',
                        'spot/trade:NAS-USDT', 'spot/trade:TRUE-USDT', 'spot/trade:SWFTC-USDT', 'spot/trade:LTC-BTC', 'spot/trade:RNT-USDT', 'spot/trade:XRP-ETH', 'spot/trade:SNT-BTC', 'spot/trade:BTG-USDT',
                        'spot/trade:CHAT-USDT', 'spot/trade:TRUE-ETH', 'spot/trade:BTM-USDT', 'spot/trade:PPT-USDT', 'spot/trade:DASH-USDT', 'spot/trade:BCD-BTC', 'spot/trade:HDAO-USDT', 'spot/trade:LRC-BTC',
                        'spot/trade:MANA-BTC', 'spot/trade:NEO-ETH', 'spot/trade:SNT-USDT', 'spot/trade:TRIO-ETH', 'spot/trade:GNT-USDT', 'spot/trade:WTC-ETH', 'spot/trade:BNT-USDT', 'spot/trade:XRP-BTC',
                        'spot/trade:MKR-USDT', 'spot/trade:BSV-USDK', 'spot/trade:ACT-USDT', 'spot/trade:THETA-USDT', 'spot/trade:MITH-BTC', 'spot/trade:WTC-USDT', 'spot/trade:NEO-BTC', 'spot/trade:MKR-BTC',
                        'spot/trade:TRIO-BTC', 'spot/trade:BTM-ETH', 'spot/trade:EC-USDK', 'spot/trade:OMG-USDT', 'spot/trade:XMR-BTC', 'spot/trade:PAY-BTC', 'spot/trade:NAS-BTC', 'spot/trade:CVC-USDT',
                        'spot/trade:ZRX-BTC', 'spot/trade:ABT-ETH', 'spot/trade:CHAT-BTC', 'spot/trade:HBAR-USDK', 'spot/trade:XLM-USDT', 'spot/trade:CVT-USDT', 'spot/trade:WXT-BTC', 'spot/trade:GAS-USDT',
                        'spot/trade:XEM-USDT', 'spot/trade:WTC-BTC', 'spot/trade:ZEC-OKB', 'spot/trade:BHP-USDT', 'spot/trade:HBAR-USDT', 'spot/trade:NEO-OKB', 'spot/trade:CTXC-ETH', 'spot/trade:LBA-USDT',
                        'spot/trade:ZRX-USDT', 'spot/trade:ONT-BTC', 'spot/trade:LINK-BTC', 'spot/trade:TOPC-USDT', 'spot/trade:ATOM-ETH', 'spot/trade:XUC-USDT', 'spot/trade:ICX-BTC', 'spot/trade:APM-USDT',
                        'spot/trade:BHP-BTC', 'spot/trade:TUSD-BTC', 'spot/trade:ATOM-USDT', 'spot/trade:FSN-USDT', 'spot/trade:NAS-ETH', 'spot/trade:CMT-USDT', 'spot/trade:DGB-BTC', 'spot/trade:TRIO-USDT',
                        'spot/trade:MITH-USDT', 'spot/trade:ONT-ETH', 'spot/trade:DASH-OKB', 'spot/trade:ABT-BTC', 'spot/trade:IOTA-ETH', 'spot/trade:BTT-USDT', 'spot/trade:CTC-BTC', 'spot/trade:HBAR-BTC',
                        'spot/trade:PST-BTC', 'spot/trade:YOU-USDT', 'spot/trade:EDO-USDT', 'spot/trade:GTO-BTC', 'spot/trade:XLM-BTC', 'spot/trade:USDC-USDT', 'spot/trade:PAX-BTC', 'spot/trade:QUN-USDT',
                        'spot/trade:INT-USDT', 'spot/trade:PST-USDT', 'spot/trade:KCASH-ETH', 'spot/trade:ZEN-USDT', 'spot/trade:MANA-ETH', 'spot/trade:LTC-ETH', 'spot/trade:EDO-BTC', 'spot/trade:WXT-USDT',
                        'spot/trade:CTXC-USDT', 'spot/trade:TUSD-USDT', 'spot/trade:LRC-ETH', 'spot/trade:THETA-BTC', 'spot/trade:DOGE-USDT', 'spot/trade:LBA-BTC', 'spot/trade:XMR-USDT', 'spot/trade:LEO-BTC',
                        'spot/trade:ACT-BTC', 'spot/trade:MDT-USDT', 'spot/trade:MCO-ETH', 'spot/trade:MDT-BTC', 'spot/trade:PMA-USDK', 'spot/trade:BAT-BTC', 'spot/trade:YOU-ETH', 'spot/trade:ORS-ETH',
                        'spot/trade:HYC-USDT', 'spot/trade:ALGO-USDT', 'spot/trade:ADA-USDT', 'spot/trade:TRX-USDK', 'spot/trade:MOF-USDT', 'spot/trade:BAT-USDT', 'spot/trade:CVT-BTC', 'spot/trade:INT-ETH',
                        'spot/trade:MDT-ETH', 'spot/trade:IOTA-BTC', 'spot/trade:UTK-USDT', 'spot/trade:ARK-BTC', 'spot/trade:EOS-USDK', 'spot/trade:GNT-BTC', 'spot/trade:LINK-ETH', 'spot/trade:DASH-BTC',
                        'spot/trade:CTC-USDT', 'spot/trade:YOU-BTC', 'spot/trade:AAC-ETH', 'spot/trade:LEO-USDT', 'spot/trade:IOST-ETH', 'spot/trade:LTC-OKB', 'spot/trade:QTUM-ETH', 'spot/trade:XEM-BTC',
                        'spot/trade:TOPC-ETH', 'spot/trade:QUN-BTC', 'spot/trade:ORS-BTC', 'spot/trade:SOC-USDT', 'spot/trade:ROAD-USDT', 'spot/trade:EGT-ETH', 'spot/trade:INT-BTC', 'spot/trade:FUN-BTC',
                        'spot/trade:MKR-ETH', 'spot/trade:APM-BTC', 'spot/trade:STORJ-ETH', 'spot/trade:ETH-USDK', 'spot/trade:VSYS-USDT', 'spot/trade:BNT-BTC', 'spot/trade:WAVES-USDT', 'spot/trade:SPND-BTC',
                        'spot/trade:NANO-USDT', 'spot/trade:AAC-USDT', 'spot/trade:SBTC-BTC', 'spot/trade:PMA-BTC', 'spot/trade:ARK-USDT', 'spot/trade:CTXC-BTC', 'spot/trade:HC-BTC', 'spot/trade:BLOC-USDT',
                        'spot/trade:AAC-BTC', 'spot/trade:VSYS-BTC', 'spot/trade:ZEN-ETH', 'spot/trade:TRX-OKB', 'spot/trade:LAMB-USDT', 'spot/trade:AST-USDT', 'spot/trade:BCH-USDK', 'spot/trade:USDC-BTC',
                        'spot/trade:CMT-BTC', 'spot/trade:ORBS-USDT', 'spot/trade:TCT-USDT', 'spot/trade:ZEN-BTC', 'spot/trade:LTC-USDK', 'spot/trade:XLM-ETH', 'spot/trade:RVN-USDT', 'spot/trade:ITC-BTC',
                        'spot/trade:MDA-USDT', 'spot/trade:ZEC-ETH', 'spot/trade:ORS-USDT', 'spot/trade:AE-USDT', 'spot/trade:ALGO-ETH', 'spot/trade:WXT-USDK', 'spot/trade:UBTC-USDT', 'spot/trade:OMG-ETH',
                        'spot/trade:KAN-USDT', 'spot/trade:SOC-BTC', 'spot/trade:BTC-USDC', 'spot/trade:FTM-USDT', 'spot/trade:CMT-ETH', 'spot/trade:SNC-BTC', 'spot/trade:XRP-USDK', 'spot/trade:HYC-ETH',
                        'spot/trade:NANO-ETH', 'spot/trade:YEE-USDT', 'spot/trade:ZRX-ETH', 'spot/trade:ZIP-USDT', 'spot/trade:YOYO-USDT', 'spot/trade:EGT-USDT', 'spot/trade:ALGO-BTC', 'spot/trade:XEM-ETH',
                        'spot/trade:OXT-USDT', 'spot/trade:BTT-BTC', 'spot/trade:ORBS-USDK', 'spot/trade:HYC-BTC', 'spot/trade:XRP-OKB', 'spot/trade:ZIL-ETH', 'spot/trade:ADA-BTC', 'spot/trade:ZIL-BTC',
                        'spot/trade:ROAD-USDK', 'spot/trade:SC-USDT', 'spot/trade:BTG-BTC', 'spot/trade:DAI-USDT', 'spot/trade:NANO-BTC', 'spot/trade:TCT-BTC', 'spot/trade:RVN-BTC', 'spot/trade:AE-BTC',
                        'spot/trade:DASH-ETH', 'spot/trade:LSK-USDT', 'spot/trade:MOF-BTC', 'spot/trade:LSK-BTC', 'spot/trade:ETM-USDT', 'spot/trade:KAN-ETH', 'spot/trade:FAIR-ETH', 'spot/trade:HC-ETH',
                        'spot/trade:GUSD-BTC', 'spot/trade:YOYO-BTC', 'spot/trade:VIB-BTC', 'spot/trade:XMR-ETH', 'spot/trade:VIB-USDT', 'spot/trade:GUSD-USDT', 'spot/trade:IQ-USDT', 'spot/trade:EGT-BTC',
                        'spot/trade:MOF-ETH', 'spot/trade:OXT-BTC', 'spot/trade:EM-USDT', 'spot/trade:BTC-DAI', 'spot/trade:SPND-USDK', 'spot/trade:ADA-ETH', 'spot/trade:WAVES-BTC', 'spot/trade:IQ-BTC',
                        'spot/trade:ETH-USDC', 'spot/trade:LET-USDT', 'spot/trade:EOS-USDC', 'spot/trade:SC-BTC', 'spot/trade:AE-ETH', 'spot/trade:DCR-BTC', 'spot/trade:PLG-USDT', 'spot/trade:ETC-USDC',
                        'spot/trade:TRX-USDC', 'spot/trade:DCR-USDT', 'spot/trade:XRP-USDC', 'spot/trade:SC-ETH', 'spot/trade:BCH-USDC', 'spot/trade:ARDR-BTC', 'spot/trade:MITH-ETH', 'spot/trade:BSV-USDC',
                        'spot/trade:ETH-DAI', 'spot/trade:KAN-BTC', 'spot/trade:AE-OKB', 'spot/trade:WAVES-ETH', 'spot/trade:SC-OKB', 'spot/trade:DCR-ETH', 'spot/trade:OKB-USDC', 'spot/trade:EGT-OKB',
                        'spot/trade:WXT-OKB', 'spot/trade:IOTA-OKB', 'spot/trade:HDAO-USDK', 'spot/trade:LTC-USDC', 'spot/trade:VSYS-USDK', 'spot/trade:FSN-USDK', 'spot/trade:FTM-USDK', 'spot/trade:PLG-USDK',
                        'spot/trade:LEO-ETH', 'spot/trade:EM-USDK', 'spot/trade:LET-BTC', 'spot/trade:DOGE-USDK', 'spot/trade:LEO-USDK', 'spot/trade:ALGO-USDK', 'spot/trade:BTT-ETH', 'spot/trade:LAMB-USDK',
                        'spot/trade:BCX-BTC'],

               'phemex': ['sBTCUSDT', 'sETHUSDT', 'sLINKUSDT', 'sXRPUSDT', 'sXTZUSDT', 'sLTCUSDT'],

               'poloniex': ['USDT_BTC', 'USDT_BCHC', 'USDT_ETH', 'USDT_TRX', 'BTC_SNX', 'BTC_XRP', 'BTC_XMR', 'BTC_ETH', 'USDC_BTC', 'USDT_BTT', 'USDT_LTC', 'USDT_BULL', 'USDT_BEAR', 'USDC_ETH', 'USDT_XMR',
                            'BTC_LTC', 'USDT_ETHBEAR', 'USDT_ETHBULL', 'BTC_ATOM', 'USDT_XRP', 'USDT_AVA', 'USDT_COMP', 'BTC_BCHABC', 'BTC_BCHSV', 'USDT_SNX', 'USDT_XFIL', 'USDC_XMR', 'BTC_AVA', 'USDT_JST',
                            'USDC_BCHSV', 'USDT_BCHSV', 'USDT_TRXBULL', 'USDT_BSVBULL', 'USDT_ATOM', 'BTC_TRX', 'BTC_SC', 'USDT_REP', 'BTC_ZRX', 'BTC_XFIL', 'BTC_DASH', 'BTC_STR', 'USDT_BCHABC', 'BTC_KNC',
                            'USDT_ETC', 'USDT_USDJ', 'BTC_REP', 'BTC_BNT', 'USDT_BSVBEAR', 'USDT_STR', 'USDT_ZEC', 'USDJ_BTC', 'USDT_BCHBEAR', 'ETH_COMP', 'USDT_TRXBEAR', 'BTC_ZEC', 'USDC_USDT', 'USDT_BAL',
                            'USDT_EOS', 'USDT_ZRX', 'USDC_BCHABC', 'USDJ_TRX', 'BTC_XEM', 'USDT_REN', 'USDT_WRX', 'BTC_ARDR', 'USDT_XRPBULL', 'BTC_FXC', 'USDC_STR', 'BTC_LRC', 'BTC_LPT', 'BTC_EOS', 'ETH_ZRX',
                            'USDT_XRPBEAR', 'USDT_BCN', 'TRX_AVA', 'USDT_DAI', 'BTC_OMG', 'USDT_QTUM', 'BTC_GNT', 'USDJ_BTT', 'USDC_ATOM', 'BTC_ETC', 'USDT_SC', 'BUSD_BTC', 'BTC_DOGE', 'USDT_MDT', 'BTC_STORJ',
                            'BTC_STRAT', 'BTC_MKR', 'USDT_MATIC', 'TRX_ETH', 'BTC_DCR', 'TRX_JST', 'USDT_DOGE', 'USDT_BCHBULL', 'USDT_EOSBULL', 'BTC_POLY', 'BTC_WRX', 'USDT_CHR', 'BTC_CHR', 'TRX_XRP',
                            'USDT_EOSBEAR', 'BTC_STEEM', 'ETH_EOS', 'USDT_MKR', 'USDC_LTC', 'BTC_SNT', 'USDT_XTZ', 'USDT_GRIN', 'USDT_DASH', 'USDC_EOS', 'BTC_NXT', 'USDT_NEO', 'BTC_MDT', 'USDT_BAT', 'USDT_LRC',
                            'ETH_BAT', 'BTC_CVC', 'BTC_SWFTC', 'BTC_LSK', 'USDT_MANA', 'USDT_BNB', 'BTC_REN', 'USDT_LSK', 'USDC_XRP', 'USDC_TRX', 'USDT_LINK', 'BTC_BAT', 'USDT_GNT', 'BTC_NMR', 'TRX_CHR', 'PAX_BTC',
                            'BTC_LOOM', 'TRX_BTT', 'BTC_BTS', 'TRX_WIN', 'ETH_ETC', 'USDT_STEEM', 'BTC_QTUM', 'BTC_MANA', 'USDT_WIN', 'BTC_LINK', 'DAI_BTC', 'USDC_ZEC', 'BTC_XTZ', 'USDT_LEND', 'ETH_ZEC', 'USDT_PAX',
                            'BTC_GAS', 'PAX_ETH', 'BTC_MATIC', 'USDC_DASH', 'USDC_ETC', 'ETH_BAL', 'USDC_GRIN', 'USDT_BUSD', 'USDT_FXC', 'BTC_LEND', 'USDT_SWFTC', 'BUSD_BNB', 'TRX_LINK', 'BTC_NEO', 'TRX_SNX',
                            'TRX_BNB', 'DAI_ETH', 'TRX_STEEM', 'BTC_FOAM', 'USDT_BVOL', 'TRX_WRX', 'TRX_MATIC', 'TRX_NEO', 'TRX_MDT', 'TRX_FXC', 'TRX_SWFTC', 'USDT_IBVOL', 'TRX_XTZ', 'BNB_BTC', 'USDC_DOGE'],


               'zb': ['btcusdt', 'eosusdt', 'etcusdt', 'ethqc', 'btcqc', 'ltcusdt', 'usdtqc', 'ethusdt', 'eosqc', 'qtumusdt', 'croqc', 'crousdt', 'xrpusdt', 'neousdt', 'hcusdt', 'hcqc', 'zbqc', 'dashusdt',
                      'gusdqc', 'sntusdt', 'ltcqc', 'gntusdt', 'omgusdt', 'usdcqc', 'xlmusdt', 'btsqc', 'xrpqc', 'ufoqc', 'qtumqc', 'neoqc', 'dogeusdt', 'usdcusdt', 'adaqc', 'ltcbtc', 'adausdt', 'dnausdt',
                      'eosbtc', 'gusdusdt', 'dnaqc', 'etcqc', 'dashqc', 'tusdusdt', 'etcbtc', 'ethbtc', 'bsvqc', 'xlmqc', 'kanqc', 'kanbtc', 'bchabcusdt', 'xrpbtc', 'aeqc', 'bchabcqc', 'bsvusdt', 'vsysqc',
                      'neobtc', 'qtumbtc', 'btsusdt', 'vsysbtc', 'trxqc', 'topcqc', 'topcusdt', 'ufousdt', 'dashbtc', 'hcbtc', 'btsbtc', 'trueqc', 'omgqc', 'lbtcqc', 'etzqc', 'tsrusdt', '1stqc', 'btmqc',
                      'grinqc', 'kncqc', 'icxqc', 'hpyqc', 'bitcnyqc', 'mcoqc', 'accusdt', 'adabtc', 'dogeqc', 'batqc', 'b91qc', 'zbusdt', 'omgbtc', 'manaqc', 'xlmbtc', 'hxqc', 'cdcqc', 'etzusdt', 'zrxqc',
                      'brcqc', 'ubtcqc', '1stusdt', 'hlcqc', 'lbtcusdt', 'qunqc', 'trxusdt', 'chatusdt', 'tvqc', 'xmrqc', 'zbbtc', 'xemqc', 'xmrusdt', 'trxbtc', 'dogebtc', 'nxwcqc', 'xwcusdt', 'trueusdt',
                      'paxusdt', 'sltqc', 'paxqc', 'leousdt', 'truebtc']
}


poloniexId = {
    336: "BNB_BTC",
    177: "BTC_ARDR",
    253: "BTC_ATOM",
    324: "BTC_AVA",
    210: "BTC_BAT",
    189: "BTC_BCH",
    236: "BTC_BCHABC",
    238: "BTC_BCHSV",
    232: "BTC_BNT",
    14: "BTC_BTS",
    15: "BTC_BURST",
    333: "BTC_CHR",
    194: "BTC_CVC",
    24:	"BTC_DASH",
    162: "BTC_DCR",
    27:	"BTC_DOGE",
    201: "BTC_EOS",
    171: "BTC_ETC",
    148: "BTC_ETH",
    266: "BTC_ETHBNT",
    348: "BTC_XFIL",
    246: "BTC_FOAM",
    317: "BTC_FXC",
    198: "BTC_GAS",
    185: "BTC_GNT",
    43:	"BTC_HUC",
    207: "BTC_KNC",
    351: "BTC_LEND",
    275: "BTC_LINK",
    213: "BTC_LOOM",
    250: "BTC_LPT",
    355: "BTC_LRC",
    163: "BTC_LSK",
    50:	"BTC_LTC",
    229: "BTC_MANA",
    295: "BTC_MATIC",
    342: "BTC_MDT",
    302: "BTC_MKR",
    309: "BTC_NEO",
    64:	"BTC_NMC",
    248: "BTC_NMR",
    69:	"BTC_NXT",
    196: "BTC_OMG",
    249: "BTC_POLY",
    75:	"BTC_PPC",
    221: "BTC_QTUM",
    353: "BTC_REN",
    174: "BTC_REP",
    170: "BTC_SBD",
    150: "BTC_SC",
    204: "BTC_SNT",
    290: "BTC_SNX",
    168: "BTC_STEEM",
    200: "BTC_STORJ",
    89:	"BTC_STR",
    182: "BTC_STRAT",
    312: "BTC_SWFTC",
    92:	"BTC_SYS",
    263: "BTC_TRX",
    359: "BTC_WRX",
    108: "BTC_XCP",
    112: "BTC_XEM",
    114: "BTC_XMR",
    117: "BTC_XRP",
    277: "BTC_XTZ",
    178: "BTC_ZEC",
    192: "BTC_ZRX",
    340: "BUSD_BNB",
    341: "BUSD_BTC",
    306: "DAI_BTC",
    307: "DAI_ETH",
    358: "ETH_BAL",
    211: "ETH_BAT",
    190: "ETH_BCH",
    347: "ETH_COMP",
    202: "ETH_EOS",
    172: "ETH_ETC",
    179: "ETH_ZEC",
    193: "ETH_ZRX",
    284: "PAX_BTC",
    285: "PAX_ETH",
    326: "TRX_AVA",
    339: "TRX_BNB",
    271: "TRX_BTT",
    335: "TRX_CHR",
    267: "TRX_ETH",
    319: "TRX_FXC",
    316: "TRX_JST",
    276: "TRX_LINK",
    297: "TRX_MATIC",
    344: "TRX_MDT",
    311: "TRX_NEO",
    292: "TRX_SNX",
    274: "TRX_STEEM",
    314: "TRX_SWFTC",
    273: "TRX_WIN",
    361: "TRX_WRX",
    268: "TRX_XRP",
    279: "TRX_XTZ",
    254: "USDC_ATOM",
    235: "USDC_BCH",
    237: "USDC_BCHABC",
    239: "USDC_BCHSV",
    224: "USDC_BTC",
    256: "USDC_DASH",
    243: "USDC_DOGE",
    257: "USDC_EOS",
    258: "USDC_ETC",
    225: "USDC_ETH",
    252: "USDC_GRIN",
    244: "USDC_LTC",
    242: "USDC_STR",
    264: "USDC_TRX",
    226: "USDC_USDT",
    241: "USDC_XMR",
    240: "USDC_XRP",
    245: "USDC_ZEC",
    288: "USDJ_BTC",
    323: "USDJ_BTT",
    289: "USDJ_TRX",
    255: "USDT_ATOM",
    325: "USDT_AVA",
    357: "USDT_BAL",
    212: "USDT_BAT",
    191: "USDT_BCH",
    260: "USDT_BCHABC",
    298: "USDT_BCHBEAR",
    299: "USDT_BCHBULL",
    345: "USDT_BCHC",
    259: "USDT_BCHSV",
    320: "USDT_BCN",
    280: "USDT_BEAR",
    337: "USDT_BNB",
    293: "USDT_BSVBEAR",
    294: "USDT_BSVBULL",
    121: "USDT_BTC",
    270: "USDT_BTT",
    281: "USDT_BULL",
    338: "USDT_BUSD",
    304: "USDT_BVOL",
    334: "USDT_CHR",
    346: "USDT_COMP",
    350: "USDT_CUSDT",
    308: "USDT_DAI",
    122: "USDT_DASH",
    262: "USDT_DGB",
    216: "USDT_DOGE",
    203: "USDT_EOS",
    330: "USDT_EOSBEAR",
    329: "USDT_EOSBULL",
    173: "USDT_ETC",
    149: "USDT_ETH",
    300: "USDT_ETHBEAR",
    301: "USDT_ETHBULL",
    318: "USDT_FXC",
    217: "USDT_GNT",
    261: "USDT_GRIN",
    305: "USDT_IBVOL",
    315: "USDT_JST",
    352: "USDT_LEND",
    322: "USDT_LINK",
    332: "USDT_LINKBEAR",
    331: "USDT_LINKBULL",
    356: "USDT_LRC",
    218: "USDT_LSK",
    123: "USDT_LTC",
    231: "USDT_MANA",
    296: "USDT_MATIC",
    343: "USDT_MDT",
    303: "USDT_MKR",
    310: "USDT_NEO",
    286: "USDT_PAX",
    223: "USDT_QTUM",
    354: "USDT_REN",
    175: "USDT_REP",
    219: "USDT_SC",
    291: "USDT_SNX",
    321: "USDT_STEEM",
    125: "USDT_STR",
    313: "USDT_SWFTC",
    265: "USDT_TRX",
    282: "USDT_TRXBEAR",
    283: "USDT_TRXBULL",
    287: "USDT_USDJ",
    272: "USDT_WIN",
    360: "USDT_WRX",
    349: "USDT_XFIL",
    126: "USDT_XMR",
    127: "USDT_XRP",
    328: "USDT_XRPBEAR",
    327: "USDT_XRPBULL",
    278: "USDT_XTZ",
    180: "USDT_ZEC",
    220: "USDT_ZRX",
}
